### ISSUE TITLE
Handling Server restart?

### ISSUE THREAD

**Issue by marudor** [hazelcast/hazelcast-nodejs-client#109]
Is there a reliable way to handle a server restart?
I've tried to catch the Error thrown if the client tries to do something on a closed socket
```javascript
try {
      raw = await this.map(options.mapName).get(key);
    } catch (e) {
      if (e.code === 'EPIPE') {
        await this.createClient(this.args);
        raw = await this.map(options.mapName).get(key);
      }
    }
````
this.createClient is used to recreate a client.
Sadly the promise to create a new promise never gets resolved.

This is using the master, not the npm package.

**Comment by marudor** [comment]
Update:
Problem is handling a reconnect when the server is not yet up again.
If I wait a few seconds before trying to above snipped after a restart it works.
So the client does not handle a starting hazelcast server nicely.

**Comment by mustafaiman** [comment]
@marudor After a server restart, client should be able to re-connect to the server within `connectionAttempLimit * connectionAttemptPeriod` milliseconds. You can change these values as you wish in configuration:
```
            var cfg = new Config.ClientConfig();
            cfg.networkConfig.connectionAttemptLimit = 5;
            cfg.networkConfig.connectionAttemptPeriod = 1000;
```

Normally, you should be able to track client state using LifecycleService. What you should do is register a lifecycle listener to your client like the following:
```
client.lifecycleService.on('lifecycleEvent', function(state) {
    // state can be `starting`, `started`, `shuttingDown` or `shutdown`
});
```
However, I saw that `shuttingDown` and `shutdown` events are not emitted in case of lost connection to cluster. I am trying to fix that now. Thank you for feedback.

**Comment by mustafaiman** [comment]
should be fixed via https://github.com/hazelcast/hazelcast-nodejs-client/pull/110
Please feel free to reopen the issue if you still have problems.

**Comment by gAmUssA** [comment]
@marudor 
if you want to contribute to `hazelcast-client` project, please, sign [contributor agreement][1]. We will be happy to see your valuable contributions.
could you remove https://www.npmjs.com/package/marudor-hazelcast-client package from NPM? We don't want to create confusion among users. 

Thank you
[1]: https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Contributor+Agreement
