### ISSUE TITLE
About EntryListener.d.ts compilation error [API-1417]

### ISSUE THREAD

**Issue by srknzl** [hazelcast/hazelcast-nodejs-client#1317]
There is known issue when "strictNullChecks" is `true` in typescript configuration. You will get an error in `EntryListener.d.ts` like the following: 
```
node_modules/hazelcast-client/lib/proxy/EntryListener.d.ts:14:5 - error TS2411: Property 'mapEvicted' of type 'MapEventListener<K, V> | undefined' is not assignable to 'string' index type 'EntryEventListener<K, V> | MapEventListener<K, V>'.

14     mapEvicted?: MapEventListener<K, V>;
       ~~~~~~~~~~

node_modules/hazelcast-client/lib/proxy/EntryListener.d.ts:15:5 - error TS2411: Property 'mapCleared' of type 'MapEventListener<K, V> | undefined' is not assignable to 'string' index type 'EntryEventListener<K, V> | MapEventListener<K, V>'.

15     mapCleared?: MapEventListener<K, V>;
       ~~~~~~~~~~


Found 9 errors in the same file, starting at: node_modules/hazelcast-client/lib/proxy/EntryListener.d.ts:7
```

This issue will be fixed in the following releases but to workaround the issue you can set "skipLibCheck" to `true` in your typescript configuration.

```json
{
    "compilerOptions": {
      "strict": true,
      "skipLibCheck": true
    }
}
```

```json
{
    "compilerOptions": {
      "strictNullChecks": true,
      "skipLibCheck": true
    }
}
```

Related issues:

1. https://github.com/hazelcast/hazelcast-nodejs-client/issues/1316
2. https://github.com/hazelcast/hazelcast-nodejs-client/issues/1286

**Comment by yuce** [comment]
Fixed by: https://github.com/hazelcast/hazelcast-nodejs-client/pull/1294 Closing.

**Comment by srknzl** [comment]
@yuce this is fixed but the issue still happens unreleased branches. maybe it is a good idea to keep the issue until every maintenance release is released
