### ISSUE TITLE
Is there a way to implement Authorization/Authentication credentials?

### ISSUE THREAD

**Issue by jackspaniel** [hazelcast/hazelcast-nodejs-client#141]
We are interoperating with a Java client that is using Authentication credentials for role-based access. We need the node side to be able to supply these credentials as well. 

It looks like [ClientAuthenticationCustomCodec](https://github.com/hazelcast/hazelcast-nodejs-client/blob/ada179595bcfd072467f1145bf8febed71afaf27/src/codec/ClientAuthenticationCustomCodec.ts) uses login credentials:

``` js
    static encodeRequest(credentials: Data, uuid: string, ownerUuid: string, isOwnerConnection: boolean, clientType: string, serializationVersion: any) {
// Encode request into clientMessage
        var clientMessage = ClientMessage.newClientMessage(this.calculateSize(credentials, uuid, ownerUuid, isOwnerConnection, clientType, serializationVersion));
        clientMessage.setMessageType(REQUEST_TYPE);
        clientMessage.setRetryable(RETRYABLE);
        clientMessage.appendData(credentials);
        clientMessage.appendBoolean(uuid === null);
        if (uuid !== null) {
            clientMessage.appendString(uuid);
        }
        clientMessage.appendBoolean(ownerUuid === null);
        if (ownerUuid !== null) {
            clientMessage.appendString(ownerUuid);
        }
        clientMessage.appendBoolean(isOwnerConnection);
        clientMessage.appendString(clientType);
        clientMessage.appendByte(serializationVersion);
        clientMessage.updateFrameLength();
        return clientMessage;
    }

```
But as far as I can tell nothing actually implements those credentials. I'm thinking maybe just in the meantime just to keep development moving, I will try forkingConnectionAuthenticator to use ClientAuthenticationCustomCodec instead of ClientAuthenticationCodec:

```js
import {ClientAuthenticationCodec} from '../codec/ClientAuthenticationCodec';
```
Thoughts on that?

**Comment by mustafaiman** [comment]
Hello @jackspaniel 
Custom Authentication is clearly missing. It should be implemented asap. Thanks for pointing it out. 

You should change https://github.com/hazelcast/hazelcast-nodejs-client/blob/master/src/invocation/ConnectionAuthenticator.ts#L27 to conform `ClientAuthenticationCustomCodec`s parameters if you are planning to use `ClientAuthenticationCustomCodec`.

Although this may work, I am investigating if there is a simpler workaround until custom authentication is implemented.

**Comment by jackspaniel** [comment]
Hey guys, FYI - we were finally able to test this and make the necessary Credentials serialization changes on the Java side. Looks good! Any ETA on when this will be published?
