### ISSUE TITLE
Error message on failure to connect doesn't properly list addresses

### ISSUE THREAD

**Issue by blicksky** [hazelcast/hazelcast-nodejs-client#146]
The error message at https://github.com/hazelcast/hazelcast-nodejs-client/blob/211161d5aa0f55773431218e1cafe51031f3012a/src/invocation/ClusterService.ts#L142 attempts to print out the list of known address to which the client failed to connect, but instead only prints out "[Object object"]. The issue is that `this.knownAddresses` is an array, so it should probably be referenced as `this.knownAddresses.join(', ')`

**Comment by gAmUssA** [comment]
@blicksky PR, please?

**Comment by blicksky** [comment]
I'm happy to provide one, but haven't had a chance to work on it just yet. I just didn't want to lose track of the issue I found while debugging something.

**Comment by blicksky** [comment]
Created PR https://github.com/hazelcast/hazelcast-nodejs-client/pull/147
