### ISSUE TITLE
Executor service for nodejs client.

### ISSUE THREAD

**Issue by Karnav123** [hazelcast/hazelcast-nodejs-client#1462]
Is there "Java Executor Service" like feature service for 
hazelcast-nodejs-client ? If not, is there any way to implement it in nodeJs application?

**Comment by yuce** [comment]
@Karnav123 Hi Kumar, Node.js doesn't have the Executor Service currently.

Having said that, would you be open to have a discussion about how you use our Node.js client? If it's OK for you, we can chat on the Hazelcast Community Slack. We have a dedicated channel for the Node.js client at: https://hazelcastcommunity.slack.com/channels/nodejs-client. You can get an invitation at: https://slack.hazelcast.com/ if you are interested to have a chat, post your questions or share your knowledge.

**Comment by Karnav123** [comment]
@yuce Thanks for your response. I have joined the slack group and explained the use case there.
