### ISSUE TITLE
Heartbeat Socket Unhandled Reject Error

### ISSUE THREAD

**Issue by pd-smith** [hazelcast/hazelcast-nodejs-client#149]
On line 66 in HeartbeatService.js, we call:
`this.client.getInvocationService().invokeOnConnection(conn, req);`

If the Hazelcast connection goes down after the client successfully connected once, the Heartbeat function throws a rejected promise that never gets handled.

> Unhandled rejection Error: This socket has been ended by the other party
>     at Socket.writeAfterFIN [as write] (net.js:270:12)
>     at ClientConnection.write (/Users/psmith/workspace/fountain/node_modules/hazelcast-client/lib/invocation/ClientConnection.js:37:21)
>     at InvocationService.send (/Users/psmith/workspace/fountain/node_modules/hazelcast-client/lib/invocation/InvocationService.js:103:20)
>     at InvocationService.invokeSmart (/Users/psmith/workspace/fountain/node_modules/hazelcast-client/lib/invocation/InvocationService.js:59:25)
>     at InvocationService.invokeOnConnection (/Users/psmith/workspace/fountain/node_modules/hazelcast-client/lib/invocation/InvocationService.js:42:21)
>     at Heartbeat.heartbeatFunction (/Users/psmith/workspace/fountain/node_modules/hazelcast-client/lib/HeartbeatService.js:37:56)
>     at Timer.listOnTimeout (timers.js:92:15)

It would be nice to catch this error and pass it as a warning to the logger.

**Comment by pd-smith** [comment]
Created PR [#150](https://github.com/hazelcast/hazelcast-nodejs-client/pull/150)

**Comment by mustafaiman** [comment]
closed via https://github.com/hazelcast/hazelcast-nodejs-client/pull/150
