### ISSUE TITLE
Do you support getAll

### ISSUE THREAD

**Issue by gwadhwa** [hazelcast/hazelcast-nodejs-client#151]
If not.....this should be ignored  and added as a feature requested.

Issue: trying to use getAll

return error:
sun.org.mozilla.javascript.internal.EvaluatorException: Cannot convert sun.org.mozilla.javascript.internal.NativeArray to java.util.Set

**Comment by gAmUssA** [comment]
@gwadhwa do you have a code to reproduce this issue?

**Comment by gwadhwa** [comment]
My Apologies for the inconvenience. GetAll worked fine with Node.js client.
The issue was with the scripting in Man-center script tab.

Please close this.
