### ISSUE TITLE
HowTo - Config object

### ISSUE THREAD

**Issue by minimok** [hazelcast/hazelcast-nodejs-client#154]
First off - congrats on this library! 
I've been a Hazelcast user in the Java world since day one, and having moved over to Node.js this is just awesome!!
I'm running through a bunch of tests, and while using localhost is fine, I'd love to see an example in teh "readme" of how to initialize the client using a config object, pref showing how one can stipulate 1 Hz server, or several, with network dets etc...

Would this be possible? It'll save some hours of trial and error :-)

**Comment by gAmUssA** [comment]
@minimok kindly check http://blog.hazelcast.com/getting-started-with-hazelcast-and-node-js-2/ and http://blog.hazelcast.com/whats-new-hazelcast-node-js-client/
And let me know if it's still unclear to you

**Comment by minimok** [comment]
That's exactly what I was looking for .Thank you so much - much appreciated!

**Comment by gAmUssA** [comment]
@minimok great! If you have any questions, welcome to our gitter channel https://gitter.im/hazelcast-incubator/hazelcast-nodejs-client?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge
