### ISSUE TITLE
Server already processed a newer authentication from client

### ISSUE THREAD

**Issue by WaVe41** [hazelcast/hazelcast-nodejs-client#168]
I'm using client 0.6.0 and cluster 3.8. After trying to compile code from samples
appears exception:
[DefaultLogger] ERROR at InvocationService: Received exception as response
RemoteException {
errorCode: 3,
className: 'com.hazelcast.client.AuthenticationException',
message: 'Server already processed a newer authentication from client with uuid 4f1cb8d4-5e1f-4ad4-a051-d14cd423d6c0. Not applying requested ownership change to 7f32e51b-8dec-4. #1
Eventually code runs successfully, but is there way to solve this problem?

**Comment by WaVe41** [comment]
I'm using client 0.6.0 and cluster 3.8. After trying to compile code from samples  appears exception: [DefaultLogger] ERROR at InvocationService: Received exception as response RemoteException { errorCode: 3, className: 'com.hazelcast.client.AuthenticationException', message: 'Server already processed a newer authentication from client with uuid 4f1cb8d4-5e1f-4ad4-a051-d14cd423d6c0. Not applying requested ownership change to 7f32e51b-8dec-4. #1 Eventually code runs successfully, but is there way to solve this problem?

**Comment by WaVe41** [comment]
I'm using client 0.6.0 and cluster 3.8. After trying to compile code from samples 
appears exception:
[DefaultLogger] ERROR at InvocationService: Received exception as response
RemoteException {
errorCode: 3,
className: 'com.hazelcast.client.AuthenticationException',
message: 'Server already processed a newer authentication from client with uuid 4f1cb8d4-5e1f-4ad4-a051-d14cd423d6c0. Not applying requested ownership change to 7f32e51b-8dec-4. #1
Eventually code runs successfully, but is there way to solve this problem?

**Comment by sancar** [comment]
Hi @WaVe41 
This check introduced on our servers to avoid inconsistent ownership info of a client among servers.
Is this exception logged by hazelcast or you ?
I would expect that this exception is just logged by hazelcast as a warning and retried without delegating to user.

**Comment by gAmUssA** [comment]
@sancar this exception logged by default by nodejs-client. What's behavior in other clients?

**Comment by sancar** [comment]
@gAmUssA By default, it is logged in java client also. In WARNING level.

**Comment by dmurgala** [comment]
Hi,
In java client correlationId starts from 1, in node-client 0.
check this com/hazelcast/client/impl/ClientEngineImpl.java:391

**Comment by mustafaiman** [comment]
@dmurgala thank you for spotting the issue with correlation id. In fact, that caused the issue. Now it is solved by https://github.com/hazelcast/hazelcast-nodejs-client/pull/172/commits/5369d85cb3cb2dbcf7002e4cab0dfcc7ce0787f1
