### ISSUE TITLE
Client logger override

### ISSUE THREAD

**Issue by bradpearson** [hazelcast/hazelcast-nodejs-client#173]
It doesn't look like there's any way to override the logging mechanism for the client, other than just 'off'. I'd like to take the log messages from the client and log them to my own logging transport. Currently they just dump to console.

**Comment by mustafaiman** [comment]
Hello @bradpearson 
You can override default logger. See winston adapter part here: https://github.com/hazelcast/hazelcast-nodejs-client/blob/master/code_samples/logging.js . This example transports logging events from hazelcast client to a custom winston instance. You can adapt that example to your needs.

**Comment by bradpearson** [comment]
@mustafaiman Thanks for pointing me in the right direction!

**Comment by mustafaiman** [comment]
I am closing this issue now. Feel free to re-open the issue if you experience any problems.
