### ISSUE TITLE
In ReliableTopic, a message is delivered to the message listener even though the listener has been removed.

### ISSUE THREAD

**Issue by kishoreannapureddy** [hazelcast/hazelcast-nodejs-client#175]
In ReliableTopic, a message is delivered to the message listener even though the listener has been removed. The listener gets removed after that.

This is because of not checking for 'cancelled' in the ring buffer's readMany's then() function in the ReliableTopicListenerRunner's next() method

**Comment by gAmUssA** [comment]
@kishoreannapureddy could you provide a reproducer?
