### ISSUE TITLE
Add Fast Aggregations to the nodejs client

### ISSUE THREAD

**Issue by lolgans** [hazelcast/hazelcast-nodejs-client#176]
Would be of great use, if fast aggregators were usable in the node-client as they are in Java. 
http://docs.hazelcast.org/docs/latest-development/manual/html/Distributed_Query/Fast_Aggregations/index.html

Especially counting by Predicate would be usefull for me.

**Comment by mustafaiman** [comment]
@lolgans implemented. will be released in 0.8.
