### ISSUE TITLE
How to cache and write through schemaless and nested JSON in Hazelcast

### ISSUE THREAD

**Issue by bhushanvadgave** [hazelcast/hazelcast-nodejs-client#177]
My usecase is I have schemaless and nested JSON objects (can contain any fields of any type). I want to cache these objects into Hazelcast and write through these objects into a document DB like Mongo. Currently I have not added any serialization code neither at Hazelcast NodeJS client nor at Hazelcast server (write through code in Java).
How can achieve this?

**Comment by gAmUssA** [comment]
@bhushanvadgave if you store JS objects `m.put(key, myObj)` you won't be able to read this in Java. if you do something like `m.put(key, JSON.stringify(myObj)` it will be saved as a JSON string in Hazelcast and you can retrieve it in Java side.

**Comment by mustafaiman** [comment]
Closing the issue now. Feel free to re-open it if you have further questions.
