### ISSUE TITLE
Method lookupOrRegisterClassDefinition can miss registration of the new portable class definition

### ISSUE THREAD

**Issue by itrambovetskyi** [hazelcast/hazelcast-nodejs-client#233]
Hi there!

I have bumped into a small issue with portable class definitions.
In the file **PotrableContext.js** exists method **lookupOrRegisterClassDefinition**:

```javascript
    PortableContext.prototype.lookupOrRegisterClassDefinition = function (portable) {
        var version = this.getClassVersion(portable);
        var definition = this.lookupClassDefinition(portable.getFactoryId(), portable.getClassId(), version);
        if (definition === null) {
            definition = this.generateClassDefinitionForPortable(portable);
            this.registerClassDefinition(definition);
        }
        return definition;
    };
```

I think that the problem can be in the next line:

```javascript
if (definition === null) {
```
Because, if we look at the method **lookupClassDefinition**

```javascript
    PortableContext.prototype.lookupClassDefinition = function (factoryId, classId, version) {
        var factory = this.classDefContext[factoryId];
        if (factory == null) {
            return null;
        }
        else {
            return factory.lookup(classId, version);
        }
    };
```

and then on **factory.lookup** (in ClassDefinitionContext.js)

```javascript
    ClassDefinitionContext.prototype.lookup = function (classId, version) {
        var encoded = ClassDefinitionContext.encodeVersionedClassId(classId, version);
        return this.classDefs[encoded];
    };
```

we can find out that **this.classDefs[encoded]** can be **undefined**.
So, the **definition** variable in the **lookupOrRegisterClassDefinition** method will be **undefined** too. And it seems like the if statement

```javascript
if (definition === null) {
```
will work a bit incorrect.

Please, let me know your thoughts.

Thanks,
Ihor T.

**Comment by mustafaiman** [comment]
Hello @itrambovetskyi , thanks for your detailed review. We appreciate the time you have taken to review this. I'll look into it. Have you encountered a bug due to this?

**Comment by itrambovetskyi** [comment]
@mustafaiman 
Yes. I have faced with the problem related to this behavior.
It's pretty simple. I have a few portable classes. When I start to work and use one of them for a first time, your library registers it with success. But when I start to use another portable class, it pass through the logic that I have described in my first comment (I have debugged it, however and for sure, I could be wrong).
As a result I have got the next error:
**TypeError: Cannot read property 'getVersion' of undefined**

it's about next code:
**file PortableSerializer.js, line 56**

```javascript
    PortableSerializer.prototype.writeObject = function (output, object) {
        var cd = this.portableContext.lookupOrRegisterClassDefinition(object);
        output.writeInt(cd.getVersion()); // <--- line 56
        var writer = new DefaultPortableWriter_1.DefaultPortableWriter(this, output, cd);
        object.writePortable(writer);
        writer.end();
    };
```

**Comment by mustafaiman** [comment]
@itrambovetskyi I changed the line you pointed also added a test. Can you verify that it solves your problem?

**Comment by itrambovetskyi** [comment]
@mustafaiman 
Yes. It helps.
Could you mention the approximate date of release with this fix?

**Comment by mustafaiman** [comment]
@itrambovetskyi This fix will go into next release which is expected around mid-january.
