### ISSUE TITLE
Jet Roadmap?

### ISSUE THREAD

**Issue by andymans** [hazelcast/hazelcast-nodejs-client#266]
Hi all,

Just an info/feature request vs issue. Any plans to support Jet features in the Node client?

Thx..

**Comment by neilstevenson** [comment]
@andymans As a workaround, have a look at https://github.com/hazelcast/hazelcast-jet-demos/tree/master/market-data-analyzer

This implements a variant of the [Command Pattern](https://en.wikipedia.org/wiki/Command_pattern) in module [CommandListener.java](https://github.com/hazelcast/hazelcast-jet-demos/blob/master/market-data-analyzer/hazelcast-grid/src/main/java/com/hazelcast/jet/demos/market/data/analyzer/CommandListener.java)

The basic idea being that Jet jobs are controlled (start/stop) by a listener on a _<String,String>_ map, a type that Node.js can work with easily -- you would add an entry ("_kafka_","_stop_") to indicate the Kafka job should be stopped, in a noun/verb style. Easily extended to take _String[]_ for the value if parameters are needed.

The jobs still have to be defined Java side.

**Comment by mustafaiman** [comment]
closing this as it is not an issue. @andymans you can use our gitter page to get a information/ask questions: https://gitter.im/hazelcast/hazelcast-nodejs-client
