### ISSUE TITLE
The hazelcast.client.statistics.enabled is not supported

### ISSUE THREAD

**Issue by sindilevich** [hazelcast/hazelcast-nodejs-client#275]
Setting the `hazelcast.client.statistics.enabled` property on Hazelcast client config does not seem to work, because of the client connection is not listed in the Hazelcast management center.

```typescript
import { Config } from "hazelcast-client";

const hazelcastConfig = new Config.ClientConfig();

hazelcastConfig.properties["hazelcast.client.statistics.enabled"] = true;
```

I would expected setting the property as in the code snippet above, would make the client appear in the clients list in the Hazelcast management center.

**Comment by mustafaiman** [comment]
Hello @sindilevich ,
Unfortunately client statistics are not supported for Node.js Client yet. I am keeping this issue open so that community interest for this feature is visible.

**Comment by mustafaiman** [comment]
Hello again @sindilevich ,
We are going to add this feature in next couple of months.

**Comment by sindilevich** [comment]
Hello @mustafaiman,

Good news! Will be waiting for further updates impatiently.
