### ISSUE TITLE
LostInvalidation test

### ISSUE THREAD

**Issue by SaitTalhaNisanci** [hazelcast/hazelcast-nodejs-client#295]
`LostInvalidation client eventually receives an update for which the invalidation event was dropped`

It looks like this test has failed on `node js 4` builder.  Also sometimes some tests fail nondeterministically on PRs and they pass when they are run again without changing any code.

**Comment by furkansenharputlu** [comment]
I ran this test 1000 times after this fix(#312). All passed. It seems resolved. I will close it when the pr is merged.
