### ISSUE TITLE
map.get with non-existent key increases near cache entry count

### ISSUE THREAD

**Issue by furkansenharputlu** [hazelcast/hazelcast-nodejs-client#325]
This bug should be fixed and a test should be added.

**Comment by mustafaiman** [comment]
This is not a bug. Near cache caches `null` values as well as non-null values. So near cache size increasing is expected. See https://github.com/hazelcast/hazelcast/blob/b1689d8dce6c0ccb48ce2b00d117b9b6a7057af2/hazelcast-client/src/test/java/com/hazelcast/client/map/impl/nearcache/ClientMapNearCacheTest.java#L738

**Comment by furkansenharputlu** [comment]
I opened this issue according to this test: https://github.com/hazelcast/hazelcast-csharp-client/blob/8ecb2dae598fe26af73cceb0a4578d8aa9ccd3c2/Hazelcast.Test/Hazelcast.Client.Test/ClientStatisticsTest.cs#L79. Maybe, C# is wrong.
