### ISSUE TITLE
Node.js client tests failures on windows

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-nodejs-client#332]
After tests from https://github.com/hazelcast/hazelcast-nodejs-client/issues/307 were fixed we hit another bulk of test failures on Windows machine for node.js client. All of them seems to be intermittent failures:

1) Listeners on reconnect restart member, listener still receives map.put event [smart=true]:
      Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

see: https://hazelcast-l337.ci.cloudbees.com/job/NodeJS-4-windows/19/console
 
2) Lost connection M2 starts, M1 goes down, client sets M2 as owner:
  TypeError: Cannot read property 'address' of null
   at Timeout._onTimeout (test\LostConnectionTest.js:57:74) 

see: https://hazelcast-l337.ci.cloudbees.com/job/NodeJS-8-windows/16/console

3) SSL Client Authentication Test via programmatic configuration "after each" hook for "ma:optional, neither knows the other should fail":
      Error: Timeout of 8000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

see: https://hazelcast-l337.ci.cloudbees.com/job/NodeJS-10-windows/17/console

**Comment by puzpuzpuz** [comment]
Closing this one as it seems to be obsolete and there are up-to-date issues for flaky tests.
