### ISSUE TITLE
Lock operations get timeout exception when member dies

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast-nodejs-client#335]
When a client waiting for a lock to be released more than invocation timeout seconds, and the member dies, clients get operation timeout exception rather than it is redirected to another member.

issue from java client https://github.com/hazelcast/hazelcast/issues/13551
fix to java client           https://github.com/hazelcast/hazelcast/pull/13552

**Comment by puzpuzpuz** [comment]
Moved this one to `3.12.4` milestone as old locks were removed in 4.0.

**Comment by puzpuzpuz** [comment]
Closed by #618
