### ISSUE TITLE
package-lock.json stuck with version 0.8

### ISSUE THREAD

**Issue by mustafaiman** [hazelcast/hazelcast-nodejs-client#338]
Apparently package-lock.json did not get updated during the release process. Client version is still 0.8 there although package.json is at 0.9.0. We need to

- [x] Check if there is any adverse effect of this discrepancy for our users
- [ ] Update release process to keep these in sync

**Comment by furkansenharputlu** [comment]
I updated the project by using `npm version`. It skips package-lock.json. I think there should not be an adverse effect.

**Comment by mustafaiman** [comment]
From npm documentation
```
version
The version of the package this is a package-lock for. This **must match** what's in package.json.
```

One disadvantage I can think of right away is that package-lock is not enforced now when we run `npm install`. Therefore, sub-dependencies may change, leading to non-repeatable builds.

According to npm documentation, this file is not published anyway. So we can assume this does not create a problem for our users downloading from npm.
