### ISSUE TITLE
Node.js Client Readme Should be Rewritten

### ISSUE THREAD

**Issue by Serdaro** [hazelcast/hazelcast-nodejs-client#340]
As depicted in the PRD https://hazelcast.atlassian.net/wiki/spaces/PM/pages/868155612/Guide+to+using+the+Node.js+Client+with+Hazelcast , we expect the Readme document to include the following chapters and sections.

Please refer to the aforementioned PRD for the content description of each section.

- [x] Make sure that the issue and the PRD outlines are compatible at the end.
- [x] Indexing should be made when all chapters are added.
- [x] Check for redundant parts and merge good content from redundant parts at the end.
- [x] Check for broken links.

## Introduction

| Content                                 | In Progress | Done  | Assigned to
|----------------------------|-------------|-------|------------
| TOC                                       |                      |    X     | Serdar
| Introduction Paragraph       |                      |   X       | Serdar
| Version Compatibility          |                      |    X      | Serdar
| Resources                            |                      |     X     | Serdar
| Release Notes                      |                      |     X     | Serdar

## Chapter 1. Getting Started

| Section                                                 | In Progress | Done  | Assigned to
|-------------------------------------|-------------|-------|-------------
| 1.1 Requirements                                 |                     |        X    | Mustafa
| 1.2 Working with Hazelcast Clusters |                     |        X    | Mustafa
| 1.2.1.1 Running Standalone Jars        |                     |     X       | Mustafa
| 1.2.1.2 Adding User Library to CLASSPATH |                     |     X       | Furkan
| 1.2.1.3 Using hazelcast-member Tool |                     |     X       | Mustafa
| 1.3 Downloading and Installing           |                     |       X     | Mustafa
| 1.4 Basic Configuration                       |                     |       X     | Mustafa
| 1.4.1 IMDG Configuration                      |                     |       X     | Mustafa
| 1.4.2 Hazelcast Client Configuration   |                     |       X     | Mustafa
| 1.5 Basic Usage                                   |                     |      X      | Mustafa
| 1.6 Code Samples                               |                     |    X        | Mustafa

## Chapter 2. Features 

| Content                                 | In Progress | Done  | Assigned to
|----------------------------|-------------|-------|------------
| List of features                    |                     |     X       | Mustafa

## Chapter 3. Configuration Overview

| Section                                                         | In Progress | Done  | Assigned to
|------------------------------------------|-------------|-------|--------------
| 3.1 Configuration Options                           |                      |      X    | Furkan
| 3.2 Importing Multiple Configurations       |                      |      X    | Furkan
| 3.3 Loading Objects and Path Resolution |                     |       X     | Furkan

## Chapter 4. Serialization

| Section                                                           | In Progress | Done  | Assigned to
|------------------------------------------ |-------------|-------|--------------
| Introduction                                                   |                      |      X   | Furkan
| 4.1 IdentifiedDataSerializable Serialization |                      |     X    | Furkan
| 4.2 Portable Serialization                              |                     |     X     | Furkan
| 4.3 Custom Serialization                               |                     |     X     | Furkan
| 4.4 Global Serialization                                 |                     |      X     | Furkan

## Chapter 5. Setting Up Client Network

| Section                                                                     | In Progress | Done  | Assigned to
|-------------------------------------------------|-------------|-------|--------------
| 5.1 Providing the Member Addresses                     |                     |      X     | Furkan
| 5.2 Setting Smart Routing                                       |                     |      X      | Furkan
| 5.3 Enabling Redo Operation                                  |                     |       X     | Furkan
| 5.4 Setting Connection Timeout                             |                     |     X       | Furkan
| 5.5 Setting Connection Attempt Limit                    |                     |     X       | Furkan
| 5.6 Setting Connection Attempt Period                  |                     |    X        | Furkan
| 5.7 Enabling TLS/SSL                                               |                     |      X      | Furkan
| 5.8 Enabling Hazelcast Cloud Discovery                |                     |     X       | Furkan

## Chapter 6. Securing Client Connection

| Section                                                                     | In Progress | Done  | Assigned to
|-------------------------------------------------|-------------|-------|-------------
| 1 TLS/SSL                                                                |                      |     X     | Furkan
| 1.1 TLS/SSL for Hazelcast Members                     |                      |     X     | Furkan
| 1.2 TLS/SSL for Hazelcast Node.js Clients           |                      |     X     | Furkan
| 1.3 Mutual Authentication                                      |                      |     X     | Furkan

## Chapter 7. Using Node.js Client with Hazelcast IMDG

| Section                                                                     | In Progress | Done  | Assigned to
|-------------------------------------------------|-------------|-------|--------------
| 7.1 Node.js Client API Overview                              |                     |    X      | Furkan
| 7.2 Node.js Client Operation Modes                      |                     |     X       | Furkan
| 7.3 Handling Failures                                               |                      |     X       | Furkan
| 7.4 Using Distributed Data Structures                   |                      |       X     | Furkan
| 7.4.1 Using Map                                                        |         X           |             | Furkan
| 7.4.2 Using MultiMap                                               |                      |      X      | Furkan
| 7.4.3 Using ReplicatedMap                                     |                      |       X      | Furkan
| 7.4.4 Using Queue                                                   |                      |      X        | Furkan
| 7.4.5 Using Set                                                         |                       |      X      | Furkan
| 7.4.6 Using List                                                         |                       |     X       | Furkan
| 7.4.7 Using Ringbuffer                                             |                       |      X      | Furkan
| 7.4.8 Using Reliable Topic                                        |          X           |            | Furkan
| 7.4.9 Using Lock                                                         |                     |      X      | Furkan
| 7.4.10 Using Atomic Long                                          |                      |      X      | Furkan
| 7.4.11 Using Semaphore                                            |                        |      X      | Furkan
| 7.4.12 Using CRDT Counter                                      |                       |       X     | Furkan
| 7.4.13 Using Flake ID Generators                              |                       |     X       | Furkan
| 7.5 Distributed Events                                               |                      |      X      | Furkan
| 7.5.1 Listening for Cluster Events                                                   |                     |      X      | Furkan
| 7.5.1.1 Membership Listener                                     |                     |      X      | Furkan
| 7.5.1.2 Distributed Object Listener                          |                     |      X      | Furkan
| 7.5.1.3 Lifecycle Listener                                          |                     |      X      | Furkan
| 7.5.2 Listening for Distributed Data Structure Events |               |       X     | Furkan
| 7.5.2.1 Map Listener                                                  |                     |      X      | Furkan
| 7.5.2.2 Entry Listener                                                |                    |      X      | Furkan
| 7.5.2.3 Item Listener                                                 |                     |       X       | Furkan
| 7.5.2.4 Message Listener                                         |                     |       X       | Furkan
| 7.6 Distributed Computing                                       |                     |      X      | Furkan
| 7.6.1 Using Entry Processor                                     |                     |      X      | Furkan
| 7.7 Distributed Query                                                |                     |     X       | Furkan
| 7.7.1 How Distributed Query Works                          |                     |     X       | Furkan
| 7.7.1.1 Employee Map Query Example                      |                    |     X       | Furkan
| 7.7.1.2 Querying by Combining Predicates with AND, OR, NOT |            |     X       | Furkan
| 7.7.1.3 Querying with SQL                                          |                     |      X       | Furkan
| 7.7.1.4 Filtering with Paging Predicates                    |                   |      X       | Furkan
| 7.7.2 Using Fast-Aggregations                                   |                    |       X     | Furkan
| 7.8 Performance                                                         |         X          |              | Furkan
| 7.8.1 Partition Aware                                                    |                    |     X       | Furkan
| 7.8.2 Near Cache                                                         |                   |      X      | Furkan
| 7.8.2.1 Configuring Near Cache                                 |                     |     X       | Furkan
| 7.8.2.2 Near Cache Example for Map                        |                    |      X      | Furkan
| 7.8.2.3 Near Cache Eviction                                       |                     |      X      | Furkan
| 7.8.2.4 Near Cache Expiration                                   |                     |      X      | Furkan
| 7.8.2.5 Near Cache Invalidation                                 |                     |      X      | Furkan
| 7.8.2.6 Near Cache Eventual Consistency                |                    |      X      | Furkan
| 7.9 Monitoring and Logging                                       |                     |      X      | Furkan
| 7.9.1 Enabling Client Statistics                                   |                     |     X     | Furkan
| 7.9.2 Logging Configuration                                       |                    |     X      | Furkan

## Chapter 8. Development and Testing

| Section                                                                     | In Progress | Done  | Assigned to
|-------------------------------------------------|-------------|--------|------------
| 8.1 Building and Using Client From Sources          |                     |      X     | Mustafa
| 8.2 Testing                                                                |                     |       X    | Mustafa

## Other Chapters

| Chapter                                                                     | In Progress | Done  | Assigned to
|-------------------------------------------------|-------------|-------|--------------
| 9. Getting Help                                                         |                     |      X    | Serdar
| 10. Contributing                                                        |                     |      X   | Serdar
| 11. License                                                                 |                     |      X   | Serdar
| 12. Copyright                                                             |                     |      X   | Serdar

**Comment by mustafaiman** [comment]
Keep in mind that README.md is reflected to https://www.npmjs.com/package/hazelcast-client as it is at release time. Therefore the whole guide will be there once the new version is released. Is this something we want? @Serdaro @furkansenharputlu

**Comment by Serdaro** [comment]
@mustafaiman Is it meaningful to have a copy of the Readme.md (e.g., named as ReadMe_InProgress.md) until it is finished?

**Comment by mustafaiman** [comment]
@Serdaro I do not want to rename Readme.md right now as there are a lot of PRs depending on it. I do not see any problem with updating it in-place as we are only adding complete-coherent sections each time.

**Comment by mustafaiman** [comment]
fixed in Readme now
