### ISSUE TITLE
add missing redoOperation key to network in ConfigBuilder

### ISSUE THREAD

**Issue by furkansenharputlu** [hazelcast/hazelcast-nodejs-client#345]
`redoOperation` key is missing in `handleNetwork` method in ConfigBuilder.

**Comment by ubeydk** [comment]
Hi @furkansenharputlu ,

I would like to make contribution this project, but it seems there is no task which is assigned no one in to-do list. Is it possible to assign this task to me if you haven't started?

**Comment by furkansenharputlu** [comment]
Hi,

Thanks for your interest! This issue is assigned to you. We look forward to your PR.

**Comment by puzpuzpuz** [comment]
Closing this one in favor of #562
