### ISSUE TITLE
Failure "Heartbeat Heartbeat stopped fired when second member stops heartbeating" on Windows

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-nodejs-client#347]
```
Heartbeat Heartbeat stopped fired when second member stops heartbeating:
Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

This error has been seen on testsuite run with node.js 8 executed on Windows machine, see:
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/NodeJS-8-windows/22/consoleFull

**Comment by mustafaiman** [comment]
This was fixed by https://github.com/hazelcast/hazelcast-nodejs-client/pull/450
