### ISSUE TITLE
BuildInfo.js containing previous version number

### ISSUE THREAD

**Issue by mustafaiman** [hazelcast/hazelcast-nodejs-client#351]
just do `npm install hazelcast-client` in any empty directory. Look for `node_modules/hazelcast_client/lib/BuildInfo.js`. It currently has version number `0.8.0` instead of `0.9.0`.

BuildInfo.js is created by `create-build-info.js` at `precompile` hook. However during release process, we first compile the library with previous version number, then we bump up the version number. We need to create `BuildInfo` after version number is bumped.

Release process should be fixed.

**Comment by furkansenharputlu** [comment]
I fixed the release process. Can you please check it ?

**Comment by mustafaiman** [comment]
After updating the release process, we performed a dry run with `npm pack` instead of `npm publish`. Everything looks ok. I am closing the issue. Thanks
