### ISSUE TITLE
Unable to install hazelcast-client via npm

### ISSUE THREAD

**Issue by manoojm** [hazelcast/hazelcast-nodejs-client#357]
I am trying to install the hazelcast-client via npm but get the following error:

2 info using npm@5.6.0
3 info using node@v8.11.4
4 verbose npm-session 74688435288a4f07
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/hazelcat-client 1333ms
8 silly fetchPackageMetaData error for hazelcat-client@latest 404 Not Found: hazelcat-client@latest
9 verbose stack Error: 404 Not Found: hazelcat-client@latest
9 verbose stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
9 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
9 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
9 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
9 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
9 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
9 verbose stack     at runCallback (timers.js:810:20)
9 verbose stack     at tryOnImmediate (timers.js:768:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:745:5)

**Comment by mustafaiman** [comment]
It looks like you mistyped `hazelcast-client` as `hazelcat-client` (missed the `s`) from the following log
```
silly fetchPackageMetaData error for hazelcat-client@latest 404 Not Found: hazelcat-client@latest
```
I can install it without a problem by typing `npm install hazelcast-client` right now. Please let us know if your problem is solved.

**Comment by manoojm** [comment]
You are absolutely right. For once I thought I could manage without copy/paste. Sorry about this. I confirm this works now.
