### ISSUE TITLE
Code sample on Entry processor is not really helpful

### ISSUE THREAD

**Issue by manoojm** [hazelcast/hazelcast-nodejs-client#358]
I have looked at the code sample on entry processor and it is kind of abstract. Can you add a sample use case like updating a value, retrieving a value. I believe both of them will have a slight difference as updating a value would require the entry processor to also run on backup nodes. The java documentation is complete but the nodejs client usage is not. 

EDIT: What I would like is sample code that helps me write an AbstractEntryProcessor, EntryProcessor code explained https://docs.hazelcast.org//docs/3.6/javadoc/com/hazelcast/map/AbstractEntryProcessor.html & https://docs.hazelcast.org//docs/3.8/javadoc/com/hazelcast/map/EntryProcessor.html respectively.

I am in the process of evaluating Hazelcast & Redis for a cache requirement in my product. It's really important for me to understand how I can use the entry processor via the client to be able to make a decision. I have used Hazelcast in the past for a enterprise java application and would like to do so even now. Any help is appreciated ASAP.

**Comment by furkansenharputlu** [comment]
You need to implement the equivalent of your `EntryProcessor` and its identified factory on the Java server side. You need to add these files to classpath of the project. So, it is not simple for now. We are working on an easy way for a user to do this. After completing it, it will be documented in detail.

Hovewer, to solve your problem now, I prepared a sample for you in my local: See: https://github.com/furkansenharputlu/hazelcast-nodejs-client/tree/addEntryProcessorCodeSample/code_samples/entryprocessor

You need to put `hazelcast-3.10.5.jar` into this directory. 
Then run `sh run.sh` command.

It will add the equivalent of the processor and its factory to server and start a server.

Hope this helps you!

**Comment by furkansenharputlu** [comment]
@manoojm Please let us know that your problem is solved, if it is solved.

**Comment by furkansenharputlu** [comment]
The most important issue before release is #340. We are preparing a detailed documentation about using Hazelcast Node.js Client. Also, there are other issues before the release. It is difficult to estimate but I think there is at least 2-3 weeks.

**Comment by manoojm** [comment]
Thank you, that sound's fine to me. Looking forward for new releases.
