### ISSUE TITLE
getOrCreateProxy function should return Promise

### ISSUE THREAD

**Issue by furkansenharputlu** [hazelcast/hazelcast-nodejs-client#370]
`getOrCreateProxy` function does not return Promise. It should return Promise. This affects all distributed data structure get methods(getMap, getList, getSet..). After the change, the followings should be made:
- [x] Refactor tests
- [x] Refactor code samples on Node.js repo
- [x] Refactor code samples on https://github.com/hazelcast/hazelcast-code-samples/tree/master/clients/nodejs
- [x] Refactor documentation
- [x] Update the code samples on org website at release time

**Comment by degerhz** [comment]
A ticket for website update request has been created. Closing this last remaining issue in this milestone.
