### ISSUE TITLE
Hazelcast logging incorrect Node.js client version number

### ISSUE THREAD

**Issue by jcaprice** [hazelcast/hazelcast-nodejs-client#417]
Hazelcast's client authentication logs are reporting the Node.js client version to be one release lower than the installed package. I have observed this with the 0.9.0 package, which is logged by Hazelcast as 0.8.0, and the 0.8.0 package, which is logged by Hazelcast as 0.7.0.

**NPM Output**
```
deasync-promise@1.0.1
  deasync@0.1.14
    bindings@1.2.1
      node-addon-api@1.6.0
hazelcast-client@0.9.0
  bluebird@3.5.0
    long@3.2.0
```

**Hazelcast Log**
```
INFO: [192.168.1.104]:5703 [dev] [3.11] Received auth from Connection[id=4, /192.168.1.104:5703->/192.168.1.104:59284, endpoint=null, alive=true, type=NODEJS_CLIENT], successfully authenticated, principal: ClientPrincipal{uuid='...', ownerUuid='...'}, owner connection: false, client version: 0.8.0
```

**Comment by furkansenharputlu** [comment]
The reason of this problem was the release process. I already fixed it. This will not happen for the next releases.

The PR(#419) is a cleanup for client version setting. I think when the PR is merged, we can close this.
