### ISSUE TITLE
hazelcast-client.json not being loaded

### ISSUE THREAD

**Issue by guylhermetabosa** [hazelcast/hazelcast-nodejs-client#445]
Hello, I'm having problems with declarative way of pass config to client.

Here is my project tree
![image](https://user-images.githubusercontent.com/6845014/50452737-b7dca080-091a-11e9-8068-392824c61e93.png)

The file `hazelcast-client.json` is in the same directory level of my  entry file app `index.js`. I've setted the group config and network config, however, the `ClientConfig` does not apply my configs and create the client with the default config, pointing to localhost instead of my addresses placed on network property at json file.

I also tried to put the environment variable `HAZELCAST_CLIENT_CONFIG` pointing to my config file, but unfortunately without success.

Am I missing something?

**Comment by mustafaiman** [comment]
Hello @guylhermetabosa `hazelcast-client.json` should be located in current working directory unless `HAZELCAST_CLIENT_CONFIG` is set. I tried this very quickly and seems to be working. Can you confirm that hazelcast-client.json file is located in current working directory when you start your application?

I also tried `HAZELCAST_CLIENT_CONFIG` pointing my config file which is located in an unrelated part of my drive. That also seems to be working for me.

I ran these tests on latest 0.10. 

Can you share which node.js client version you are using and log outputs?
Thanks

**Comment by guylhermetabosa** [comment]
Hello @mustafaiman, the version of nodejs-client does not support my hazelcast version. Sorry for not closing this issue.

Regards,
