### ISSUE TITLE
'MembershipListener sees member removed event' test failure on Windows

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-nodejs-client#453]
_master_ (commit c27bb3863a20813e5e3d862d258ca9c3decedc19)

Failed on windows for all NodeJS jobs, e.g.: https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/NodeJS-10-windows/60/

```
MembershipListener sees member removed event:
      Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

**Comment by puzpuzpuz** [comment]
Closing as this issue is no longer valid for the latest `master`
