### ISSUE TITLE
Make client work when addresses configured via different interface than members

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast-nodejs-client#460]
Clients and members were forced to configure the same interface when adding a member address to config.

https://github.com/hazelcast/hazelcast/pull/14104
With this prd on the java side, we have relaxed the rules. As long as hostnames are resolved to the same IP when DNS lookup made on the client side following setups are allowed.

1. Member hostname <-> client different hostname
2. Member ip       <-> client different hostname
3. Member hostname <-> client ip

Same needs to be applied to nodejs client

**Comment by puzpuzpuz** [comment]
Node.js client v4.1 seems to include all recent changes from Java client (e.g. see #713 as an example of recent changes). Considering this, I think it should be safe to close this issue. @sancar  WDYT?

**Comment by sancar** [comment]
How about adding these tests to the nodejs client to verify that. 
https://github.com/hazelcast/hazelcast/pull/14104/files#diff-eb8cf9135b3d0b362103f723f2e11bcf32c21785f0a0f7608d0eec9de13e63f7R114

**Comment by puzpuzpuz** [comment]
Good idea. I'll add similar tests into the node client test suite.
