### ISSUE TITLE
sync versions of operations

### ISSUE THREAD

**Issue by enesakar** [hazelcast/hazelcast-nodejs-client#461]
putSync()
getSync() etc

I am tired of putting await.

**Comment by mustafaiman** [comment]
I assume you are asking for these in order to use them in simple test and demos. Otherwise, sync calls to these methods should not ever be used. I think we should not introduce an API that is never going to be used in production. Otherwise, it is just extra workload for us to maintain.

**Comment by enesakar** [comment]
makes sense
