### ISSUE TITLE
Custom credentials is not available in declarative configuration

### ISSUE THREAD

**Issue by kairojya** [hazelcast/hazelcast-nodejs-client#470]
It looks like you can't do the following declaratively. I don't see credentials in the [full config example](https://github.com/hazelcast/hazelcast-nodejs-client/blob/master/test/declarative_config/configurations/full.json) or [config schema](https://github.com/hazelcast/hazelcast-nodejs-client/blob/master/config-schema.json).

```
var Config = require('hazelcast-client').Config;
var cfg = new Config.ClientConfig();
cfg.customCredentials = new UsernamePasswordCredentials('admin', 'password1', '127.0.0.1');
```

**Comment by puzpuzpuz** [comment]
Closing this one as v4.0 changed the configuration API and `customCredentials` are available there.
