### ISSUE TITLE
TypeError: address.indexOf is not a function

### ISSUE THREAD

**Issue by vaibhav-praeeo** [hazelcast/hazelcast-nodejs-client#477]
Getting error after clean installation of  **npm i hazelcast-client** . 
error :  address.indexOf is not a function
stack : "TypeError: address.indexOf is not a function\n    at Function.AddressHelper.createAddressFromString (\node_modules\hazelcast-client\lib\Util.js:218:41)

Error at :

`static createAddressFromString(address: string, defaultPort?: number): Address {
        const indexBracketStart = address.indexOf('[');`

When using :
`let config = new Config.ClientConfig();
  config.networkConfig.addresses = [{host: '192.168.1.28', port: '5701'}];`

I had to comment out whole function and return only

` return new Address(address.host, address.port);`

**Comment by mustafaiman** [comment]
Hi @vaibhav-praeeo,
If you are using a recent version of Node.js client, `config.networkConfig.addresses` is a list of strings now. You should do `config.networkConfig.addresses.push('192.168.1.28:5701');`. Let us know if this solves your problem.

**Comment by vaibhav-praeeo** [comment]
@mustafaiman , Thank you very much. config.networkConfig.addresses.push('192.168.1.28:5701'); solved problem. 👍
