### ISSUE TITLE
Client could not reconnect when server restarts

### ISSUE THREAD

**Issue by bhushanvadgave** [hazelcast/hazelcast-nodejs-client#480]
#### Versions
Hazelcast NodeJS Client version: 3.12
Hazelcast server version: 3.12

#### Client Code
`
    let clientConfig = new HConfig.ClientConfig();
    clientConfig.networkConfig.addresses.push(`${HZ_HOST}:${HZ_PORT}`);
    clientConfig.networkConfig.connectionAttemptLimit = -1;
`

#### Issue Description
When Hazelcast node restarts, 
**HZ NodeJS client starts giving the following error**
`
Error: This socket has been ended by the other party
[DefaultLogger] WARN at PartitionService: Error while fetching cluster partition table from6621ff08-5c6c-42f0-956e-2ba7a0cb2176
Error: Error: This socket has been ended by the other party
[DefaultLogger] ERROR at ConnectionAuthenticator: Invalid Credentials
[DefaultLogger] ERROR at ConnectionAuthenticator: Invalid Credentials
`

**HZ server starts giving the following error**
`
13:29:11.692 [hz._hzInstance_1_dev.priority-generic-operation.thread-0] WARN  c.h.c.i.p.t.AuthenticationMessageTask - [192.168.0.117]:5701 [dev] [3.12] Received auth from Connection[id=144, /192.168.0.117:5701->/192.168.0.117:64435, qualifier=null, endpoint=null, alive=true, type=NONE] with principal ClientPrincipal{uuid='23adbac6-021b-47a7-914d-d6d9347f1ceb', ownerUuid='6621ff08-5c6c-42f0-956e-2ba7a0cb2176'}, authentication failed
`

**Comment by gulcesirvanci** [comment]
Hi @bhushanvadgave . The cause of this problem seems like the authentication process. Can you verify the group name is correct when  HZ server restarts?

**Comment by burakcelebi** [comment]
Hey @bhushanvadgave, any update? Thanks!

**Comment by puzpuzpuz** [comment]
Closing this one due to inactivity.
