### ISSUE TITLE
How to retrieve all clients connected in a cluster

### ISSUE THREAD

**Issue by manoojm** [hazelcast/hazelcast-nodejs-client#484]
Is there a way to retrieve all the clients connected to a cluster from one client? like 

clients = localClient.getClientService().getConnectedClients() 

I actually need the connected clients for their id's.

**Comment by mdumandag** [comment]
Hi @manoojm 

There is no way to do that in the client directly. 

But, Hazelcast Management Center has a REST API in which you can get the information you need. To do that, start a Management Center instance as described [here](https://docs.hazelcast.org/docs/management-center/3.12.1/manual/html/index.html#deploying-and-starting) and enable REST as described [here](https://docs.hazelcast.org/docs/management-center/3.12.1/manual/html/index.html#enabling-clustered-rest). Then, use [this](https://docs.hazelcast.org/docs/management-center/3.12.1/manual/html/index.html#client-statistics-resource) or [that](https://docs.hazelcast.org/docs/management-center/3.12.1/manual/html/index.html#client-endpoints-resource) endpoint to get the information you need.

**Comment by manoojm** [comment]
ok thanks.
