### ISSUE TITLE
Cannot surpress logging

### ISSUE THREAD

**Issue by pbrickell** [hazelcast/hazelcast-nodejs-client#503]
config.properties['hazelcast.logging'] = 'off';

Does not stop default logger on 3.12.1

**Comment by gulcesirvanci** [comment]
Hi, there is an error in README. I fixed this. It will be merged asap. You can use the following example. 
 `cfg.properties['hazelcast.logging.level'] = LogLevel.OFF;`

**Comment by pbrickell** [comment]
Thanks, that works for me. I'm figuring there is no way to set that with strings. I have an external config file & now have to switch to the LogLevel. It's OK but a tad annoying.

**Comment by mdumandag** [comment]
Hi @pbrickell 

Do you mean declarative configuration with `hazelcast-client.json` when you said setting config with strings ? If that is the case, `LogLevel.OFF`, `LogLevel.INFO` etc. are just integer values. You can close the logging with JSON configuration with the setting below

```json
{
"properties": {
        "hazelcast.logging.level": -1
    }
}
```

**Comment by pbrickell** [comment]
@mdumandag 

Sorry I wasn't clear. We have an external configuration server and the schema for it defines the log level as a string from an enum (trace, debug, etc). We are using this to programatically set the log level. I now have a switch statement to map from string to LogLevel. It works fine but it's a little inelegant. I'm not going to sweat it.

**Comment by mdumandag** [comment]
Oh I see, actually setting log level as string makes more sense. This way, it will also resembles the way you set levels in the `winston`. We may change that in the future, thanks for the clarification

**Comment by pbrickell** [comment]
No problem. Thanks all for the assistance.
