### ISSUE TITLE
Reliable topic message listener does not recover after client reconnect

### ISSUE THREAD

**Issue by manoojm** [hazelcast/hazelcast-nodejs-client#507]
Hi, 

I have a scenario where in after a client reconnect, the topic's message listener fails to receive any message that is published onto the topic. Unfortunately, I cannot share code that I have in place for IP reasons. Is there a standard procedure that should be run in the event of a client recovery?

This issue is happening in our production so any quick help will be greatly helpful.

**Comment by manoojm** [comment]
>> PING... any help?

**Comment by mdumandag** [comment]
Hi @manoojm 

Reliable topic is backed by a ring buffer proxy on the member side. So, when the cluster is restarted, you lost the underlying ring buffer and the listener on the client side is terminated.

**Comment by manoojm** [comment]
@mdumandag ,, i haven't restarted my cluster.. the client and server are both running throughout the test.. but after they recover from network event and reconnect... The reconnect happens just fine but the listener does not get the events anymore... Is there a suggestion on how we handle such scenarios?

**Comment by mdumandag** [comment]
@manoojm, are you seeing the following log ? https://github.com/hazelcast/hazelcast-nodejs-client/blob/master/src/proxy/topic/ReliableTopicListenerRunner.ts#L86

My guess is that when the client disconnects from the cluster the request to read from the ring buffer fails and the listener is being invalidated. I didn't tested my theory yet, but will try and inform you.

If that is the case, you may use to lifecycle events to re-register your listener.

**Comment by manoojm** [comment]
@mdumandag .. no I am not seeing that log. And if I re-register then I might end up having two listeners and process the tasks twice.. (unless I can make sure the topic is not registered anymore).. Is there a way to do that?

**Comment by puzpuzpuz** [comment]
@manoojm is this issue still actual? Do you face it each time when a client reconnects?

**Comment by manoojm** [comment]
Not each time & when it happens, I do not see the log statement that was pointed in this discussion. Again, unregistering and registering again is an alternative but will not work reliably as we might loose items in between & doing it aggresively is counter productive.

**Comment by burakcelebi** [comment]
Closing due to the inactivity. Please let us know if you have a reproducer. We are always happy to help you. Thanks!
