### ISSUE TITLE
Distributed queue size is incorrect even when there are items in the queue

### ISSUE THREAD

**Issue by manoojm** [hazelcast/hazelcast-nodejs-client#508]
Items are added in quick succession to the distributed queue and the size returns incorrect value(value less than what is in the queue) when checked immediately. Is this even reliable?

NOTE: - In my client, I have a listener for items added.. and I check the size of the queue after this is executed and NOT in the item listener implementation. Any response is much appreciated.

**Comment by puzpuzpuz** [comment]
Queues should be reliable under normal conditions (no split brain, at least one backup exists).

> In my client, I have a listener for items added.. and I check the size of the queue after this is executed and NOT in the item listener implementation.

Could you clarify how exactly you're doing the size check?

**Comment by manoojm** [comment]
So, I have a listener on queue add and while the listener code is doing something, if I check for size using queue.size(), it returns value less than the recently added item. If I run the size after the listener code has finished, then it returns the right value. If this is intended, then please close this issue.

**Comment by puzpuzpuz** [comment]
> So, I have a listener on queue add and while the listener code is doing something, if I check for size using queue.size(), it returns value less than the recently added item.

Could you provide the listener code? I wonder how do you run the asynchronous `.size()` operation in the listener which is synchronous.

**Comment by manoojm** [comment]
I am not saying I run asynchronous code from within synchronous listener.. I was saying that if I do not let the synchronous listener finish and invoke .size from another flow in the same node process, the size does not include the newly added item. Is this an intended behavior? Are we expected to see the new item only after listener code has finished execution?

**Comment by puzpuzpuz** [comment]
> I am not saying I run asynchronous code from within synchronous listener.. I was saying that if I do not let the synchronous listener finish and invoke .size from another flow in the same node process, the size does not include the newly added item.

I was asking for code as lots of events may actually happen in between the listener invocation and the subsequent `.size()` operation, including operations that modify the queue. So, it's hard to reason about correctness of the check, without understanding the exact scenario and having a sample code.

As for this question:

> Are we expected to see the new item only after listener code has finished execution?

The answer is no, listener execution doesn't affect item visibility, i.e. it should become visible once you've added an item into the queue.

**Comment by manoojm** [comment]
ok.. closing this as this is not an issue for us anymore. Thanks for the help in clarifying the query.
