### ISSUE TITLE
No entry value on remove entry event in Map listener

### ISSUE THREAD

**Issue by manoojm** [hazelcast/hazelcast-nodejs-client#510]
Why is there no entry value on remove event on an Map entry listener even when include value is set to true?

**Comment by puzpuzpuz** [comment]
The listener should receive the value. Here is a sample snippet:
```js
'use strict';

const Client = require('hazelcast-client').Client;

async function mapTest() {
    const client = await Client.newHazelcastClient();
    const map = await client.getMap('my-map');

    const listener = {
        removed: (entryEvent) => console.log('Got entry in the listener:', entryEvent)
    };

    await map.addEntryListener(listener, undefined, true);

    await map.put('foo', 'bar');
    await map.remove('foo');

    return client;
}

mapTest()
    .then((client) => {
        console.log('Done');
        return client.shutdown();
    })
    .catch(console.log);
```

In the console output you should see something like this:
```
Got entry in the listener: EntryEvent {
  name: 'my-map',
  key: 'foo',
  value: undefined,
  oldValue: 'bar',
  mergingValue: undefined,
  member:
...
```

The `oldValue` field is exactly what you're looking for.

Could you share the corresponding part of your code, if you still think it's bug?

**Comment by puzpuzpuz** [comment]
@manoojm did the above comment answer your question? Let me know if you any questions.

**Comment by manoojm** [comment]
@puzpuzpuz apologies for not being able to respond to this sooner. We have changed our code to not need the entry value on map remove. So, I will have to bring back the old changes to confirm if its working for me. But, as far as I can remember, the oldValue was not available for me when I logged this issue. But, I am closing this case for now. Thanks for your help.
