### ISSUE TITLE
ReliableTopicProxy: Cannot read property 'add' of undefined

### ISSUE THREAD

**Issue by manoojm** [hazelcast/hazelcast-nodejs-client#511]
Unhandled Rejection: TypeError: Cannot read property 'add' of undefined
newblend_2         |     at ReliableTopicProxy.trySendMessage (/opt/ssdc/newblend/node_modules/hazelcast-client/lib/proxy/topic/ReliableTopicProxy.js:136:25)
newblend_2         |     at ReliableTopicProxy.addWithBackoff (/opt/ssdc/newblend/node_modules/hazelcast-client/lib/proxy/topic/ReliableTopicProxy.js:131:14)
newblend_2         |     at ReliableTopicProxy.publish (/opt/ssdc/newblend/node_modules/hazelcast-client/lib/proxy/topic/ReliableTopicProxy.js:91:29)

Running into the above error when I try to publish multiple (parallel burst) events on reliable topic. Any help please?

**Comment by manoojm** [comment]
This is blocking us from deploying our app in production so any assistance at the earliest will be much appreciated.

**Comment by puzpuzpuz** [comment]
@manoojm thanks for the heads-up. I'll take a look at this issue today and get back to you.

**Comment by puzpuzpuz** [comment]
@manoojm do you have a minimal reproducer source code for this issue? The issue you faced should happen because of a non-initialized internal ringbuffer, but I don't see how this can be happening.

**Comment by manoojm** [comment]
I Am afraid I dont have it. The issue is intermittent and when it happens, have always noticed that the events were submitted to the topic in a fast pace (almost in parallel). I realized as much from the source that ringbuffer turned out to be null but strange because submissions before and after pass even when one in the middle fails. It happened in our staging env again today morning,

node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'add' of undefined
at ReliableTopicProxy.trySendMessage (/opt/ssdc/nborchestrator/node_modules/hazelcast-client/lib/proxy/topic/ReliableTopicProxy.js:136:25)
at ReliableTopicProxy.addWithBackoff (/opt/ssdc/nborchestrator/node_modules/hazelcast-client/lib/proxy/topic/ReliableTopicProxy.js:131:14)
at ReliableTopicProxy.publish (/opt/ssdc/nborchestrator/node_modules/hazelcast-client/lib/proxy/topic/ReliableTopicProxy.js:91:29)

Not sure if adding a retry would help solve the problem but again it will have to be on app code right? or Is there some such provision in the client implementation?

**Comment by puzpuzpuz** [comment]
> Not sure if adding a retry would help solve the problem but again it will have to be on app code right?

I'm not sure if a retry would help as it looks like `ITopic` (reliable topic) object is not initialized properly for some reasons and that breaks further operation calls.

Could you at least share fragments of your code where you obtain `ITopic` and publish events? This could give me some basement for further experiments.

**Comment by manoojm** [comment]
I could but it will take me sometime to make something meaningful and share with you. But, in my defense, I do not do anything fancy. Following is roughly what I do in my node server:
1. Start server,
2. Connect to HZ member via the client lib
3. Upon successful connect, subscribe to the topic
4. Now, node can accept API requests. So, when client initiates an op, it will post processing, publish a message on the same topic.  

Sample code for subscribe and publish as below:

publish: async (topicName, message) => {
            let reliableTopic = await _client.getReliableTopic(topicName);
            return await reliableTopic.publish(message);
        },
        subscribe: async (topicName, listener) => {
            let reliableTopic = await _client.getReliableTopic(topicName);
            return reliableTopic.addMessageListener(listener);
        },

Hope this helps.

**Comment by puzpuzpuz** [comment]
Thanks for sharing this. Your update gave me a clue on what might go wrong. Going to address this bug (on this or, in the worst case, on the next week).

**Comment by puzpuzpuz** [comment]
BTW as a temp workaround to mitigate this issue you could do the following. You need to initialize the topic first (somewhere before you create an instance of your class with `.publish()`/`.subscribe()`):
```js
let reliableTopic = await _client.getReliableTopic(topicName);
```

and then pass it into your class' constructor and use it there:
```js
publish: async (topicName, message) => {
    return await this.reliableTopic.publish(message);
},
subscribe: async (topicName, listener) => {
    return this.reliableTopic.addMessageListener(listener);
},
```

This way `.getReliableTopic()` for the same topic won't be called concurrently (and that's where the bug lives), thus you won't face the issue.

**Comment by puzpuzpuz** [comment]
@manoojm thanks for reporting this issue once again. The bugfix will be included into the next release, yet I don't know yet when to expect it.

**Comment by manoojm** [comment]
I see that this is added to 3.12.2 milestone.. can someone please confirm when can we expect this release? We really need this fix as otherwise we may have to make code changes to accomodate the workaround and redo it once the fix is released.

**Comment by puzpuzpuz** [comment]
AFAIK v3.12.2 should be release next week.

@mdumandag please correct me if I'm wrong.

**Comment by manoojm** [comment]
Thank you.. and will this release support the new CP subsystem data structures (from this post https://github.com/hazelcast/hazelcast-nodejs-client/issues/509, the current version doesn't)?

**Comment by mdumandag** [comment]
Hi @manoojm , yes the 3.12.2 version should be released next week. We are doing the release verification tests right now. However, CP subsytem will not be included in this version. This feature is projected for the 4.0 release

**Comment by manoojm** [comment]
Ok @mdumandag  & @puzpuzpuz for confirming this. We plan to use the hazelcast locks heavily in our enterprise application and the deprecated locks have issues in the event of a network partition which seems to have been fixed as part of fenced lock (available in the CP subsystem).. any chance u can provide a tentative 4.0 release time?

**Comment by mdumandag** [comment]
@manoojm It is planned to release 4.0 version around May but this is highly tentative.

**Comment by burakcelebi** [comment]
@manoojm thanks for letting us know your need! I've just added you as a sponsor the CP Subsystem for Node.js which is already planned for Node.js Client 4.0 (as Metin has already mentioned above). Thanks!

**Comment by mdumandag** [comment]
@manoojm 3.12.2 is released on npm. You can use it now

**Comment by manoojm** [comment]
Thank you @mdumandag
