### ISSUE TITLE
Invocation Timeout Handling

### ISSUE THREAD

**Issue by mustafaiman** [hazelcast/hazelcast-nodejs-client#52]
When Invocation does not get a response, we should handle it by retrying the invocation if necessary.

**Comment by mustafaiman** [comment]
@GhostInAMachine What is the status of this issue. I remember that you said it would be resolved https://github.com/hazelcast/hazelcast-nodejs-client/pull/50#discussion_r57287028

**Comment by GhostInAMachine** [comment]
It only retries when there is an exception, not when there is no response.

**Comment by mustafaiman** [comment]
Should we retry when there is no response, too? I think the point of having invocation timeout is that.

**Comment by GhostInAMachine** [comment]
I don't quite remember to what did we agree regarding the timeout handling, but we certainly did not want to retry the invocation just because there was no response for X seconds.
