### ISSUE TITLE
Convert tests to ES6 syntax

### ISSUE THREAD

**Issue by puzpuzpuz** [hazelcast/hazelcast-nodejs-client#523]
Currently tests (both unit and integration ones) are written with ES5 syntax which may be error-prone under certain conditions (say, due to variable hoisting). We should start using ES6 syntax (`const`/`let`, arrow functions, etc.) in tests.

Note: certain language features may be not available in Node v4. So, this task potentially depends on #519.

**Comment by smitchell41** [comment]
I'd like to work on this, if I can!

**Comment by puzpuzpuz** [comment]
@smitchell41 first of all, many thanks for your interest! For sure you can pick this issue. I suggest you to wait for #522 to be merged before working on it. That PR involves many changes in tests. I'll post an update here once it's merged, which should happen soon.

**Comment by puzpuzpuz** [comment]
@smitchell41 as #522 is merged now, there are no blockers for this improvement anymore. Please let me know if you need any help on this one. Looking forward for your contributions! 👍

**Comment by smitchell41** [comment]
@puzpuzpuz I'm so sorry, but I've ended up with a lot more to do this summer than I expected, and I don't think I have time to work on this. Thank you for your help, though.

**Comment by puzpuzpuz** [comment]
@smitchell41 no problem at all. Thanks for your interest in the project.

**Comment by EaswarDSharma** [comment]
can i take this one up? is it assigned to someone?
and these are all the files to convert right?
[https://github.com/hazelcast/hazelcast-nodejs-client/tree/master/test](url)

**Comment by puzpuzpuz** [comment]
@EaswarDSharma I'm currently updating many tests as a part of #554. In the meantime you could pick up any other issue labeled with `good first issue`.

As the the directory with tests, then yes, you have pointed at the right one.
