### ISSUE TITLE
Events for ready/error etc.

### ISSUE THREAD

**Issue by Yomanz** [hazelcast/hazelcast-nodejs-client#525]
Is there a way to listen for a "ready" event so I can take action within my application.

It would also be very useful to add this for errors and possibly when new shards are added etc.

**Comment by puzpuzpuz** [comment]
> Is there a way to listen for a "ready" event so I can take action within my application.

What do you mean by `ready` event? Cluster connection? If yes, then promise returned by `Client.newHazelcastClient(config)` is what you need. If it successfully resolves, then the client was able to establish initial connection. Also, you may listen to lifecycle events:
https://github.com/hazelcast/hazelcast-nodejs-client#7513-lifecycle-listener
 
> It would also be very useful to add this for errors and possibly when new shards are added etc.

Probably, you mean membership events:
https://github.com/hazelcast/hazelcast-nodejs-client#7511-membership-listener

**Comment by Yomanz** [comment]
Perfect, thanks very much.
