### ISSUE TITLE
Roadmap for distributed execution

### ISSUE THREAD

**Issue by cemremengu** [hazelcast/hazelcast-nodejs-client#527]
In my opinion one of the best things about hazelcast is its distributed execution/scheduling ability. I couldn't see any info about that for this client though even on the roadmap 😞 

Any more details from the maintainers about that?

**Comment by puzpuzpuz** [comment]
Currently we don't have plans for distributed execution of JS (Node.js) code. But you may use Java client/member's capabilities for execution Java code:
https://docs.hazelcast.org/docs/4.0.1/manual/html-single/index.html#distributed-computing

Does this answer your question or you've meant something different?

**Comment by cemremengu** [comment]
Yes, thanks for the response!
