### ISSUE TITLE
Switch to native promises instead bluebird

### ISSUE THREAD

**Issue by puzpuzpuz** [hazelcast/hazelcast-nodejs-client#529]
Native promises have increased performance in Node.js 10+, so [bluebird](https://github.com/petkaantonov/bluebird/) doesn't have a significant advantage anymore. Also, bluebird maintainers advice to switch to native promises, when possible. We should experiment with the switch, do some benchmarks and decide whether we should switch now.

If we do the switch, we don't need #524 at all.

**Comment by EaswarDSharma** [comment]
I'd like to do this, can someone please help me getting started ,what should i know, where to start,  what is expected to be done by the end and lastly which part of documentation should i know well? thank you !

**Comment by puzpuzpuz** [comment]
@EaswarDSharma first of all, I'd like to thank you for you interest in the project. You should probably start with reading this documentation section and then get familiar with the code base (a high-level familiarity should be ok for this task):
https://github.com/hazelcast/hazelcast-nodejs-client/blob/master/DOCUMENTATION.md#9-development-and-testing

As the next task, you should find all usages of `bluebird` across the code base and try to port them to native promises. There are several places where non-standard (`bluebird` implementation specific) methods are used, but it should be pretty straight-forward to migrate those. Let me know if you experience any blockers.

The last step would be to remove `bluebird` dependency from `package.json`.

**Comment by EaswarDSharma** [comment]
Got this error while running tests locally after downloading https://pastebin.com/NrNnjtrW

**Comment by puzpuzpuz** [comment]
@EaswarDSharma it looks like `4.0.2-SNAPSHOT` artifact is not available. I've created #561 to fix tests. To avoid waiting for that PR to land you could apply those changes to your local code base.

**Comment by puzpuzpuz** [comment]
@EaswarDSharma #561 is now merged. Please let me know if you face any issues.

**Comment by EaswarDSharma** [comment]
2 tests are failing. thought due to ssl problems and googled a lot about it but unabled to solve finally. my OS is ubuntu 20.04 LTS
https://pastebin.com/H3Pgs5mR --- this is short output log.

https://pastebin.com/ucMtFFQD  ---- the total long original version

**Comment by puzpuzpuz** [comment]
@EaswarDSharma `test/ssl/ClientSSLTest.js` tests SSL feature which requires open source version of IMDG. So, it should be marked as an enterprise test (see [this commented line](https://github.com/hazelcast/hazelcast-nodejs-client/blob/master/test/ssl/ClientSSLTest.js#L39)) and skipped when OS version is in use.

I'm going to fix that as a part of #554, so please ignore those two failing test cases for now.

**Comment by puzpuzpuz** [comment]
Hi @EaswarDSharma. Were you able to make some progress on this one?

**Comment by EaswarDSharma** [comment]
sorry for the delay. Since there are many files and directories, I thought of writing a c++ program to find bluebird string ( "'bluebird';" ) and print the files that have this string. i started with namespace filesystem later found boost library to be better and now i presently am working on this. Any suggestion on this? and i didn't find gitter channel mentioned , to be active. could you please mention an active community group?

**Comment by puzpuzpuz** [comment]
@EaswarDSharma thanks for the update. The simplest way to find bluebird imports would be to use `grep` utility or search capabilities of an editor (e.g. VS Code). As for the gitter channel, here it is: https://gitter.im/hazelcast/hazelcast

**Comment by EaswarDSharma** [comment]
after removing lines that import bluebird into code , i'm always getting this error at `Promise.Resolver<T>`.  as `'Promise' only refers to a type, but is being used as a namespace here.ts(2702)` for `deferred: Promise.Resolver<ClientMessage>;`
checked but not getting how to solve this.
We used used `each( )` from bluebird but now we are eliminating it. how to do it in native way? [found something here](https://stackoverflow.com/questions/41607804/promise-each-without-bluebird) but not sure how to implement.
and here i'm getting these errors in this file and other files. why am i getting these and how to solve them?
[code and errors included here](https://pastebin.com/QTj6PwqW)

**Comment by puzpuzpuz** [comment]
@EaswarDSharma `Promise.Resolver` is a custom interface specific to `bluebird`. There is no such thing for native promises, so you should port it into the code base.

**Comment by EaswarDSharma** [comment]
**port it into the code base** sorry i didn't get it. could explain what should i do in detail plz

**Comment by puzpuzpuz** [comment]
> **port it into the code base** sorry i didn't get it. could explain what should i do plz

@EaswarDSharma you should port the interface into client's code base. So, that interface will be defined in `src/util/Util.ts`.

**Comment by puzpuzpuz** [comment]
@EaswarDSharma as we're moving closer v4.0 release, I'm going to pick up this task. In the meanwhile, if you're still interested in contributing to the library, you could pick another `good first issue`, like the #569 one.
