### ISSUE TITLE
Enable TypeScript compiler flags

### ISSUE THREAD

**Issue by puzpuzpuz** [hazelcast/hazelcast-nodejs-client#530]
We're using an outdated TypeScript version and should update to the latest stable one. Also, we should consider using strict compiler flags as they can help with finding potential issues earlier.

cc @aigoncharov

**Comment by puzpuzpuz** [comment]
Partially addressed in #553 (TS version upgrade)

**Comment by srknzl** [comment]
I want to try enabling [strict](https://www.typescriptlang.org/tsconfig#strict) flag. Not sure if I should do it after #797 is merged as it includes many changes. Should we disable [strictPropertyInitialization](https://www.typescriptlang.org/tsconfig#strictPropertyInitialization), since we have these type of usages:
```typescript
/** @internal */
export class Task {
    timeoutId: NodeJS.Timer;
    intervalId: NodeJS.Timer;
}
```

with `strict:true` and `strictPropertyInitialization: false`, there are 306 errors in master branch's code.

**Comment by puzpuzpuz** [comment]
> I want to try enabling [strict](https://www.typescriptlang.org/tsconfig#strict) flag.

That's awesome. I agree that #797 should get merged before starting this work. As for `strictPropertyInitialization`, we probably should disable it for now. One more thing to notice here is that it would be nice to upgrade to TypeScript v4.

**Comment by srknzl** [comment]
> That's awesome. I agree that #797 should get merged before starting this work

Let's start this then

**Comment by srknzl** [comment]
We should be aware of this comment before starting https://github.com/hazelcast/hazelcast-nodejs-client/issues/310#issuecomment-401773406

**Comment by srknzl** [comment]
Let's bump the version to 4, then enable strict flag as well to keep things simple and seperated. See #816

**Comment by srknzl** [comment]
As seen in the error below and the comment https://github.com/hazelcast/hazelcast-nodejs-client/issues/310#issuecomment-401773406, when strictNullChecks is enabled auto generated codec files are giving errors. The auto generation code should change or we can exclude  strictNullChecks

```
src/codec/builtin/MapCodec.ts:62:9 - error TS2322: Type 'Map<K, V> | null' is not assignable to type 'Map<K, V>'.
  Type 'null' is not assignable to type 'Map<K, V>'.

62         return CodecUtil.nextFrameIsNullFrame(clientMessage) ? null : this.decode(clientMessage, keyDecoder, valueDecoder);
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```
