### ISSUE TITLE
Decide on defining custom credentials

### ISSUE THREAD

**Issue by mdumandag** [hazelcast/hazelcast-nodejs-client#541]
4.0 Java client uses [ClientSecurityConfig](https://docs.hazelcast.org/docs/latest/javadoc/com/hazelcast/client/config/ClientSecurityConfig.html) to get custom credentials. We are using `config.customCredentials` for that purpose. We need to decide on whether we want something like `ClientSecurityConfig` before releasing 4.0 client.

**Comment by puzpuzpuz** [comment]
As v4.0 is already released, the new ClientSecurityConfig should be added in backwards-compatible manner.
