### ISSUE TITLE
Test Failure - Heartbeat stopped fired when second member stops heartbeating in 3.12.x

### ISSUE THREAD

**Issue by mdumandag** [hazelcast/hazelcast-nodejs-client#548]
[This](https://github.com/hazelcast/hazelcast-nodejs-client/blob/3.12.x/test/heartbeat/HeartbeatFromServerTest.js#L39) test failed by timing out twice in the #546 which in unrelated. We should investigate the reasoning behind this.

**Comment by puzpuzpuz** [comment]
@mdumandag I don't see this test failing in recent builds since, at least, the beginning of September. Considering this, I'd prefer to close this issue and reopen it if/when necessary. WDYT?

**Comment by puzpuzpuz** [comment]
Closing this one.
