### ISSUE TITLE
Update Hazelcast Cloud documentation and code sample

### ISSUE THREAD

**Issue by mdumandag** [hazelcast/hazelcast-nodejs-client#551]
We have a fix for the issue reported here for the 3.12.x branch. https://github.com/hazelcast/hazelcast-python-client/issues/207.

However, we cannot use 4.0 clients with Hazelcast Cloud yet, so it is unclear for me how should we update the parts reported in the issue for the master branch.

Once we can use 4.0 clients with Hazelcast Cloud, we should update our documentation and code samples accordingly.

See: https://github.com/hazelcast/hazelcast-nodejs-client/pull/550

**Comment by puzpuzpuz** [comment]
@mdumandag AFAIR the documentation and Cloud Discovery plugin is now up to date. If my memory is correct, I'm going to close this issue.

**Comment by mdumandag** [comment]
The code snippet is correct, but we need to update the documentation around it as reported by Jaromir. Basically, Hazelcast cloud can now communicate via clear text if configured so, and there is no need to mention orchestrator to the user as it is something internal about the system

See the https://github.com/hazelcast/hazelcast-python-client#enabling-hazelcast-cloud-discovery. Also sent a small correction to the Python documentation https://github.com/hazelcast/hazelcast-python-client/pull/263/files

**Comment by puzpuzpuz** [comment]
Closed with #714
