### ISSUE TITLE
Client can't connect to the cluster member

### ISSUE THREAD

**Issue by srknnn** [hazelcast/hazelcast-nodejs-client#565]
Hello,
I try since a week about this problem. But i could not find any solution.  I have a docker image running in my local. I can add and get 3 data with key to the cluster. But I take an error at forth data. it seems like time out problem. Also cluster members have not error logs. I think problem is not about cluster members.  Problem appears after put several data. Could you help please?

Here is my post link:
https://stackoverflow.com/questions/63244076/i-cant-add-data-more-than-3-to-hazelcast-image-cluster-with-node-js/63247767#63247767

**Comment by puzpuzpuz** [comment]
Hi @srknnn. Could you provide a reproducer for your problem?

**Comment by srknnn** [comment]
```
```
Hi @puzpuzpuz. I am trying to make a simple application for connect to local docker Hazelcast cluster members in Node js.
firstly I runned these commands for starting cluster;

$ docker run -p 5701:5701 hazelcast/hazelcast:3.12.3
$ docker run -p 5702:5701 hazelcast/hazelcast:3.12.3
$ docker run 6edef36a4fec  ( 6edef36a4fec is imageID)

![image](https://user-images.githubusercontent.com/23223573/89646224-0f4b3c80-d8c4-11ea-8e78-7bfc339c5c0b.png)

after that I created an app.js and I used httpCreateServer for make request from browser with querystring and My Code is here;

```
```
var http = require('http');
const querystring = require('querystring');
const { Console } = require('console');
var server = http.createServer((function (req, response) {

	if(req.url.indexOf("favicon") > 0){
		response.end("Hello");
		return;
	}

	response.writeHead(200,
		{ "Content-Type": "text/plain" });


	var deneme = req.url.split("?");

	var key = querystring.parse(deneme[1]).key;
	var reqType = querystring.parse(deneme[2]).reqType;
	var mapName = querystring.parse(deneme[3]).mapName;
	var printedValue="";

	// console.log(req);

	var HazelcastClient = require('hazelcast-client').Client;
	var Config = require('hazelcast-client').Config;

	var config = new Config.ClientConfig();
	// config.networkConfig.addresses = [{host: '127.0.0.1', port: '5701'}];
	config.networkConfig.addresses.push('127.0.0.1:5701');

	var map = {};


	var hazelCastRequest = function (key) {
		HazelcastClient
			.newHazelcastClient(config)
			.then((hazelcastClient) => {
				map = hazelcastClient.getMap(mapName).then(function (mp) {
					map = mp;
					if(reqType=="post"){
						 insertPerson(map, key);
					}
					if(reqType=="get"){
						readPerson(map, key);
					}
				});
                // hazelcastClient.shutdown();
			}).catch( function (error){
				console.log("clientErrorDeneme", error);
			});
	};

	hazelCastRequest(key);


	var printValue = function (text, value) {
		console.log(text + JSON.stringify(value));
	};

	var insertPerson = function (map, key) {
		var person = {}
		if (key == "key1") {
			person = {
				key: key,
				firstName: "Joe",
				lastName: "Doe",
				age: 42
			};
		}
		if (key == "key2") {
			person = {
				key: key,
				firstName: "serkan",
				lastName: "Soydam",
				age: 42
			};
		}
		if (key == "key3") {
			person = {
				key: key,
				firstName: "serkan3",
				lastName: "Soydam3",
				age: 42
			};
		}
		if (key == "key4") {
			person = {
				key: key,
				firstName: "serkan4",
				lastName: "Soydam4",
				age: 42
			};
		}

		map.put(key, person).then(function (previousValue) {
			printValue("Previous value: ", previousValue);
		}).catch( function (error){
			console.log("error1", error);
		});
	};

	var readPerson = function (map, key) {
		map.get(key).then(function (value) {
			printValue("Value for key=1: ", value);
			printedValue=value.key;
		}).catch( function (error){
			console.log("error2", error);
		});
	};

response.end(printedValue);

}));
server.listen(7001);
```

And I runned this app in debug mode and I made a post request something like that from browser;
 http://localhost:7001/?key=key2?reqType=post?mapName=persons 
And I got this Data 
 http://localhost:7001/?key=key2?reqType=get?mapName=persons 

![image](https://user-images.githubusercontent.com/23223573/89647168-c98f7380-d8c5-11ea-93a9-78e7e81b2ac6.png)

But I see some Errors in vsCode Debug Console 

![image](https://user-images.githubusercontent.com/23223573/89647430-3c005380-d8c6-11ea-9699-1f24866369e2.png)

Also when I try to add a few more data, I took this error in catch;

![image](https://user-images.githubusercontent.com/23223573/89648367-c85f4600-d8c7-11ea-95f6-89f77fec3ab7.png)

**Comment by srknnn** [comment]
And I runned this app in debug mode and I made a post request something like that from browser;
 http://localhost:7001/?key=key2?reqType=post?mapName=persons 
And I got this Data 
 http://localhost:7001/?key=key2?reqType=get?mapName=persons 

![image](https://user-images.githubusercontent.com/23223573/89647168-c98f7380-d8c5-11ea-93a9-78e7e81b2ac6.png)

But I see some Errors in vsCode Debug Console 

![image](https://user-images.githubusercontent.com/23223573/89647430-3c005380-d8c6-11ea-9699-1f24866369e2.png)

Also when I try to add a few more data, I took this error in catch;

![image](https://user-images.githubusercontent.com/23223573/89648367-c85f4600-d8c7-11ea-95f6-89f77fec3ab7.png)

**Comment by puzpuzpuz** [comment]
@srknnn there are a couple of problems in your script. First of all `response.end(printedValue);` was called synchronously, which is probably not what you wanted, as it's supposed to contain value read from the map.

The next problem was Hazelcast client initialization. The client is stateful and assumes that you start a single instance of the client and reuse it when handling all requests.

We have some code samples that might help to understand the client API better: https://github.com/hazelcast/hazelcast-nodejs-client/tree/3.12.x/code_samples

I've addressed both problems and modified the script a bit and it seems to be working correctly for me. Here it is:

```js
'use strict';

var http = require('http');
const querystring = require('querystring');
var HazelcastClient = require('hazelcast-client').Client;
var Config = require('hazelcast-client').Config;

function hazelCastRequest(key, reqType, mapName, cb) {
    var map;
    hazelcastClient.getMap(mapName).then(function (mp) {
        map = mp;
        if (reqType == "post") {
            insertPerson(map, key, cb);
        }
        if (reqType == "get") {
            readPerson(map, key, cb);
        }
    }).catch(function (error) {
        console.log("clientErrorDeneme", error);
    });
}

function insertPerson(map, key, cb) {
    var person = {}
    if (key == "key1") {
        person = {
            key: key,
            firstName: "Joe",
            lastName: "Doe",
            age: 42
        };
    }
    if (key == "key2") {
        person = {
            key: key,
            firstName: "serkan",
            lastName: "Soydam",
            age: 42
        };
    }
    if (key == "key3") {
        person = {
            key: key,
            firstName: "serkan3",
            lastName: "Soydam3",
            age: 42
        };
    }
    if (key == "key4") {
        person = {
            key: key,
            firstName: "serkan4",
            lastName: "Soydam4",
            age: 42
        };
    }

    map.put(key, person).then(function (previousValue) {
        printValue("Previous value: ", previousValue);
        cb('OK');
    }).catch(function (error) {
        console.log("error1", error);
    });
};

function readPerson(map, key, cb) {
    map.get(key).then(function (value) {
        printValue("Value for key=1: ", value);
        cb(value.key);
    }).catch(function (error) {
        console.log("error2", error);
    });
};

function printValue(text, value) {
    console.log(text + JSON.stringify(value));
};

var hazelcastClient;

var server = http.createServer((function (req, response) {
    if (req.url.indexOf("favicon") > 0) {
        response.end("Hello");
        return;
    }

    response.writeHead(200,
        { "Content-Type": "text/plain" });

    var deneme = req.url.split("?");

    var key = querystring.parse(deneme[1]).key;
    var reqType = querystring.parse(deneme[2]).reqType;
    var mapName = querystring.parse(deneme[3]).mapName;

    hazelCastRequest(key, reqType, mapName, (result) => response.end(result));
}));

var config = new Config.ClientConfig();
// config.networkConfig.addresses = [{host: '127.0.0.1', port: '5701'}];
config.networkConfig.addresses.push('127.0.0.1:5701');

HazelcastClient.newHazelcastClient(config)
    .then((client) => {
        hazelcastClient = client;
        server.listen(7001);
        console.log('Server started listening on 7001');
    });
```

And here is the output:
```
$ curl http://localhost:7001/?key=key1?reqType=post?mapName=persons
OK
$ curl http://localhost:7001/?key=key1?reqType=get?mapName=persons
key1
$ curl http://localhost:7001/?key=key3?reqType=post?mapName=persons
OK
$ curl http://localhost:7001/?key=key3?reqType=post?mapName=persons
OK
$ curl http://localhost:7001/?key=key3?reqType=get?mapName=persons
key3
```

**Comment by srknnn** [comment]
Hi @puzpuzpuz . I Tried your script solutions. But the problem and errors are same. What can i try something else?

**Comment by puzpuzpuz** [comment]
@srknnn error logs make me thinking that one of members is not reachable for Node.js client. Could you describe once again how you start members? Most likely there is something wrong in Docker configuration.

**Comment by srknnn** [comment]
@puzpuzpuz  sure. First of all I write this command;

$ docker run -p 5701:5701 hazelcast/hazelcast:3.12.3

and result;

![image](https://user-images.githubusercontent.com/23223573/89707235-f8b0ee00-d974-11ea-8210-d5a656b81a48.png)

After that 

$ docker run -p 5702:5701 hazelcast/hazelcast:3.12.3 

And result;
![image](https://user-images.githubusercontent.com/23223573/89707258-2d24aa00-d975-11ea-912e-c755455bad37.png)

so I look images and about i run image about hazelcast(I don't know that is it necessary But I still run )

![image](https://user-images.githubusercontent.com/23223573/89707324-93a9c800-d975-11ea-9f77-2ac7eb40cb41.png)

$ docker run 6edef36a4fec

![image](https://user-images.githubusercontent.com/23223573/89707344-c05ddf80-d975-11ea-88a9-ca259c5f7d6e.png)

I tried to  explain in order

**Comment by puzpuzpuz** [comment]
I've just tried to run the same commands on my machine (Ubuntu 18.04, node v12.18.3, Docker version 19.03.6, build 369ce74a3c), then tried starting the server and sending various requests many times, and saw no errors in logs. All requests were handled successfully.

**Comment by srknnn** [comment]
@puzpuzpuz I understand. The docker works at windows 10 in my local. I guess the problem related my machine

**Comment by puzpuzpuz** [comment]
@srknnn sounds good. I'll be waiting to hear back from you.

**Comment by srknnn** [comment]
hello @puzpuzpuz  I tested the problem in another machines but it didn't work. But i solved problem. source of the problem is docker command. I had given the e JAVA_OPTS="-Dhazelcast.local.publicAddress in the docker commands. Thank you for your help.
