### ISSUE TITLE
Migrate tests to async/await syntax

### ISSUE THREAD

**Issue by puzpuzpuz** [hazelcast/hazelcast-nodejs-client#569]
As this is a relatively big change, the plan is to do it incrementally.

The following test could be used for some inspiration: https://github.com/hazelcast/hazelcast-nodejs-client/blob/9c1c2d10b8d5a2dc74fa21ddca3676a3e66cfb25/test/ClientRedoEnabledTest.js

**Comment by sudiptog81** [comment]
This issue can be worked upon incrementally in a series of PRs, for example. I went through the code base, the tests currently using `done()` might need some attention. I was able to migrate some, and the tests were passing for the most part. Better to discuss an approach to tackle this one.

**Comment by puzpuzpuz** [comment]
> I went through the code base, the tests currently using `done()` might need some attention.

Test with `done()` are mostly listener-related and in many cases it's fine to leave them as is (i.e. with direct promise usage). This issue primarily means those tests that have a "linear" async calls flow and can be easily migrated to async/await. And, certainly, it's better to start with a small PR first.

**Comment by sudiptog81** [comment]
Submitting next PR by EOD IST.

**Comment by sudiptog81** [comment]
I'll try to take on the remaining tests in a single PR.
