### ISSUE TITLE
npm: publish to npm.org

### ISSUE THREAD

**Issue by gAmUssA** [hazelcast/hazelcast-nodejs-client#63]
Publish js artifacts to npm + typings

References:

* http://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html
* http://blog.charto.net/node-js/Publishing-TypeScript-based-modules-on-npm/

**Comment by gAmUssA** [comment]
I think we need to resolve this https://github.com/hazelcast/hazelcast-nodejs-client/issues/61 first.

**Comment by mustafaiman** [comment]
We are planning to push 0.2 to npm repository. This will be solved by then.

**Comment by gAmUssA** [comment]
:+1:  @mustafaiman I'm well aware of it. that's why I attached this issue to 0.2 milestone!

**Comment by mustafaiman** [comment]
https://www.npmjs.com/package/hazelcast-client
