### ISSUE TITLE
Configure eslint for tests

### ISSUE THREAD

**Issue by puzpuzpuz** [hazelcast/hazelcast-nodejs-client#635]
We currently don't lint source code of tests which is not nice. The configuration should be placed in the `./test` subdir and `lint` script should be updated in `package.json`.

**Comment by katieraby** [comment]
Can I take this one on please?

**Comment by puzpuzpuz** [comment]
@katieraby sure. Let me assign it to you, if you don't mind.

**Comment by katieraby** [comment]
Pull request for this issue: https://github.com/hazelcast/hazelcast-nodejs-client/pull/637 😄
