### ISSUE TITLE
Add support for Kubernetes discovery

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-nodejs-client#643]
`hazelcast-nodejs-client:4.0.0` has no discovery for Kubernetes

**Comment by puzpuzpuz** [comment]
@neilstevenson Node.js client v4.1 (#703 to be more precise) will introduce support for external client public address discovery. It's not a specialized discovery plugin (which is better), but it should provide necessary discovery behavior. Considering this, is it a good idea to close this issue?

**Comment by neilstevenson** [comment]
What's needed is that the Node.js client can connect to a cluster in Kubernetes, whether DNS or API is used, and whether or not the client is inside or outside of Kubernetes.

In other words, the Node.js client needs to be able to fully work with Kubernetes deployments in all styles.

It doesn't really matter whether is uses the discovery plugin, duplicates the logic of the discovery idea (although this doesn't sound good) or has some different solution. All that matters is it works somehow.

**Comment by puzpuzpuz** [comment]
> In other words, the Node.js client needs to be able to fully work with Kubernetes deployments in all styles.

That's the plan. As for the DNS scenario (the client and all members are running in the same k8s cluster), it already works with 4.0.2 version of the client. Integration team recently published a guide on the topic with some samples: https://guides.hazelcast.org/kubernetes/
