### ISSUE TITLE
Flaky MigratedDataTest [API-1243]

### ISSUE THREAD

**Issue by puzpuzpuz** [hazelcast/hazelcast-nodejs-client#646]
`MigratedDataTest` got flaky for some reasons. See http://jenkins.hazelcast.com/job/NodeJS-pr-builder/647/testReport/junit/(root)/killing%20a%20server%20migrates%20data%20to%20the%20other%20node,%20migrated%20data%20has%20new%20uuid,%20near%20cache%20discards%20data%20with%20old%20uuid/MigratedDataTest_killing_a_server_migrates_data_to_the_other_node__migrated_data_has_new_uuid__near_cache_discards_data_with_old_uuid/ as an example

**Comment by srknzl** [comment]
Opening it failed again. windows, client commit 198850c18da92ae6d6438757136fe2e6ef0a1ff8

```
1) MigratedDataTest
       killing a server migrates data to the other node, migrated data has new uuid, near cache discards data with old uuid:
     Error: Partition 136 was not moved to 06c39ce0-43ca-4ab2-b2b6-cccc2fb744e9
      at Timeout.resolveOrTimeout [as _onTimeout] (test\integration\backward_compatible\parallel\nearcache\MigratedDataTest.js:57:33)
```

**Comment by srknzl** [comment]
https://github.com/hazelcast/hazelcast-nodejs-client/runs/5430419727?check_suite_focus=true
