### ISSUE TITLE
A dead link/anchor in the npm main page

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast-nodejs-client#655]
The [npm page](https://www.npmjs.com/package/hazelcast-client) says:
```
NOTE: For the sake of brevity we are going to omit boilerplate parts in the above code snippet. Refer to the Code Samples section to see samples with the complete code.
```
![image](https://user-images.githubusercontent.com/158619/97705840-fe6e2980-1ab4-11eb-90e8-ab1f643a6be3.png)

When I click at the "Code Samples section" then nothing happens.

**Comment by puzpuzpuz** [comment]
The correct link should be https://github.com/hazelcast/hazelcast-nodejs-client/tree/master/code_samples. Going to fix it in the next patch release.
