### ISSUE TITLE
Listener registration does not wait for all connections

### ISSUE THREAD

**Issue by puzpuzpuz** [hazelcast/hazelcast-nodejs-client#679]
Listener registration does not wait for individual connections, but rather for the first one. We should use `Promise.all()` instead.

See: https://github.com/hazelcast/hazelcast-nodejs-client/blob/f6fddf41157472f82783e51ae798a5c1776a6fef/src/ListenerService.ts#L211

Refs: #677 (fix for 4.1)

**Comment by yuce** [comment]
This is already implemented.
