### ISSUE TITLE
Flaky MapProxyTest [API-1200]

### ISSUE THREAD

**Issue by puzpuzpuz** [hazelcast/hazelcast-nodejs-client#724]
http://jenkins.hazelcast.com/job/NodeJS-12-master/93/testReport/junit/(root)/putTransient_withTTL/MapProxyTest_Near_Cache__true_putTransient_withTTL/

```
putTransient_withTTL.MapProxyTest Near Cache: true putTransient_withTTL (from Near Cache_ true)

Error Message
expected null to equal 'val10'
Stacktrace
AssertionError: expected null to equal 'val10'
    at Context.<anonymous> (test/map/MapProxyTest.js:325:32)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by srknzl** [comment]
This(all the tests with ttl in general in MapProxyTest) failed in some gh actions runs opening.

**Comment by srknzl** [comment]
https://github.com/hazelcast/hazelcast-nodejs-client/pull/1104/files seems to solve the problem. We just need to backport it to maintenance branches. Note that the pr is sent after the issue is reopened, and forgot to be linked to the issue when sent.
