### ISSUE TITLE
Avoid passing client instance into service constructors

### ISSUE THREAD

**Issue by puzpuzpuz** [hazelcast/hazelcast-nodejs-client#731]
Currently most of services expect client instance in their ctors (an [example](https://github.com/hazelcast/hazelcast-nodejs-client/blob/3c4104a517e85d3882a1756b452ab773608302a2/src/HazelcastClient.ts#L136)), so the instance serves as a "god object". We should pass concrete services/components instead in order to make the code and tests more maintainable.

**Comment by srknzl** [comment]
Does this issue includes "Manager"' or just "Services". For example do we want to change ConnectionManager construction?

**Comment by puzpuzpuz** [comment]
> Does this issue includes "Manager"' or just "Services". For example do we want to change ConnectionManager construction?

@srknzl it includes all internal modules (services, managers, etc.) that currently accept client instance while it's sufficient for them to accept more narrow set of objects.

**Comment by srknzl** [comment]
Did you see the pr? @puzpuzpuz

**Comment by puzpuzpuz** [comment]
> Did you see the pr? @puzpuzpuz . Changed a lot there, so I am curious they are ok

Yes, I saw it. Going to review it later today.

**Comment by srknzl** [comment]
I am going to add this shortcut in constructors to #707
Instead of
```typescript
class User {
  private name: string;
  private surname: string;
  private age: number;

  constructor(name: string, surname: string, age: number) {
    this.name = name;
    this.surname = surname;
    this.age = age;
  }
}
```
this is shorter:

```typescript
class User {
  constructor(
    private name: string,
    private surname: string,
    private age: number
  ) {}
}
```

One more point, why we use this: AImpl class implements A interface and AImpl is used as type where AImpl class is required. Example with ClientConfig:
```typescript
constructor(
        clientConfig: ClientConfig,
        private readonly logger: ILogger,
        private readonly clusterFailoverService: ClusterFailoverService
    ) {
        this.translateToAddressProvider = new TranslateAddressProvider(clientConfig as ClientConfigImpl, logger);
    }
```

my proposition is to use ClientConfig instead in TranslateAddressProvider constructor

**Comment by srknzl** [comment]
One more thing, we can use getters.

e.g In LoggingService, instead of this 

```typescript
getLogger(): ILogger {
        return this.logger;
}
```
if we use 

```typescript
get logger(): ILogger {
        return this._logger; // renamed logger private attribute to _logger, could also name this getter differently
}
```
then we can use `this.client.loggingService.logger`

**Comment by puzpuzpuz** [comment]
> I am going to add this shortcut in constructors to #797

Not sure if that make code more readable, but I don't have a strong opinion here.

> Some classes implements a single interface and the class is used as type where the class is required.

We do that for config related classes in order to separate public API from the implementation. With config the user is free to pass a plain JS object which should meet requirements of the interface and then we internally create a proper `*Impl` instance out of it. As for `ClientConfigImpl` in particular, we could use this class internally instead of the interface and avoid additional casting.

**Comment by puzpuzpuz** [comment]
> One more thing, we can use getters.

Not sure if that makes the code more readable once again, but for internal modules we're free to start using property getters.

**Comment by srknzl** [comment]
> We do that for config related classes in order to separate public API from the implementation.

It's usage is not limited to config related classes though.

> Not sure if that make code more readable, but I don't have a strong opinion here.

Yeah it does not but it is shorter code and thus, easier to write.

**Comment by puzpuzpuz** [comment]
> It's usage is not limited to config related classes though. e.g PartitionServiceImpl usage as type

`PartitionService` interface is a part of public API, while the class is kept internal. We could remove the interface and mark internal methods as `@internal`, but I don't see any value in such change over what we have now.

**Comment by srknzl** [comment]
> > It's usage is not limited to config related classes though. e.g PartitionServiceImpl usage as type
> 
> `PartitionService` interface is a part of public API, while the class is kept internal. We could remove the interface and mark internal methods as `@internal`, but I don't see any value in such change over what we have now.

Ok I guess I should learn what are public first. Lets skip this for now then
