### ISSUE TITLE
Rewrite scripts in Node.js

### ISSUE THREAD

**Issue by puzpuzpuz** [hazelcast/hazelcast-nodejs-client#752]
We have some scripts for downloading and running RC in `./scripts`. They're written as a bash script for *nix and batch file for Windows. To reduce the maintenance burden we could rewrite them in Node.js.

Refs: https://github.com/hazelcast/hazelcast-python-client/pull/299/

**Comment by srknzl** [comment]
Handled both, could you check if I miss something @puzpuzpuz
