### ISSUE TITLE
[TRACKING ISSUE] Cleanup: Remove the look up to member list on client invocation

### ISSUE THREAD

**Issue by ghost** [hazelcast/hazelcast-nodejs-client#757]
The tracking issue for the Java side PR.

**Cleanup: Remove the look up to member list on client invocation**

See https://github.com/hazelcast/hazelcast/pull/16602 for details.

---

In 3.12, invocations were opening connections. To avoid opening
a connection to a non-member, we had a member-list check.
In 4.0, it is not needed anymore since connections will not be opened
by invocations.

Related TargetNotMemberException check is also not needed on retry.

**Comment by puzpuzpuz** [comment]
Closing as Node.js client already has the fix.
