### ISSUE TITLE
[TRACKING ISSUE] Add validations to connection retry config and fix sleep time calcula…

### ISSUE THREAD

**Issue by ghost** [hazelcast/hazelcast-nodejs-client#764]
The tracking issue for the Java side PR.

**Add validations to connection retry config and fix sleep time calcula…**

See https://github.com/hazelcast/hazelcast/pull/17018 for details.

---

…tion

There were missing validation checks on the ConnectionRetryConfig.
The following checks are added

initialBackoffMillis -> [0, inf)
maxBackoffMillis -> [0, inf)
multiplier -> [1.0, inf)
jitter -> [0.0, 1.0]
clusterConnectionTimeoutMillis -> [0, inf)

Also, `actualSleepTime` calculation was wrong. It was calculating
sleep time in range
[currentBackoffMilis - jitter * currentBackoffMillis, currentBackoffMillis].

**Comment by puzpuzpuz** [comment]
`actualSleepTime` calculation has the fix, but the `ConnectionRetryConfig` validation part is missing.
