### ISSUE TITLE
[TRACKING ISSUE] Log terminate in finest when the client is closing

### ISSUE THREAD

**Issue by ghost** [hazelcast/hazelcast-nodejs-client#767]
The tracking issue for the Java side PR.

**Log terminate in finest when the client is closing**

See https://github.com/hazelcast/hazelcast/pull/17153 for details.

---

ReliableTopicMessageListener should not warn the user when
the client is shutting down. InstanceNotActiveException is
already in finest. This pr makes ClientNotActiveException log level
finest too.

fixes https://github.com/hazelcast/hazelcast/issues/17070

**Comment by puzpuzpuz** [comment]
Closed with #567
