### ISSUE TITLE
[TRACKING ISSUE] Added labels to ClientEndpoint#toString() method

### ISSUE THREAD

**Issue by ghost** [hazelcast/hazelcast-nodejs-client#769]
The tracking issue for the Java side PR.

**Added labels to ClientEndpoint#toString() method**

See https://github.com/hazelcast/hazelcast/pull/17181 for details.

---

Fixes https://github.com/hazelcast/hazelcast/issues/17178

**Comment by puzpuzpuz** [comment]
Closing as `ClientInfo` class in Node.js client doesn't have (and there is no need for it) `toString()` method.
