### ISSUE TITLE
[TRACKING ISSUE] custom load balancer declarative configuration

### ISSUE THREAD

**Issue by ghost** [hazelcast/hazelcast-nodejs-client#771]
The tracking issue for the Java side PR.

**custom load balancer declarative configuration**

See https://github.com/hazelcast/hazelcast/pull/17415 for details.

---

Fixes https://github.com/hazelcast/hazelcast/issues/17228

Changes:

- "custom" balancer type was introduced (as suggested)
- XML, YAML config loading supports new balancer type
- Spring bean class name or reference is also supported for "custom" type

I'm aware that there have to be seperate PRs for other branches. Are you guys able to cherry pick this change onto 4.0.z and 4.z branches or do I have to open separate PRs? (this will take some time)

Can you help review this first?

**Comment by puzpuzpuz** [comment]
Closing as Node.js client supports programmatic config API only.
