### ISSUE TITLE
[TRACKING ISSUE] Add local checks for count argument of CountDownLatch#trySetCount

### ISSUE THREAD

**Issue by ghost** [hazelcast/hazelcast-nodejs-client#773]
The tracking issue for the Java side PR.

**Add local checks for count argument of CountDownLatch#trySetCount**

See https://github.com/hazelcast/hazelcast/pull/17528 for details.

---

* `CountDownLatch#trySetCount` implementations were doing a remote call even when called with a non-positive `count`. This PR adds local checks to mitigate the problem
* Also improves javadoc consistency for some CP data structures

**Comment by puzpuzpuz** [comment]
Closing as Node.js client has this fix.
