### ISSUE TITLE
[TRACKING ISSUE] Fix exit condition in client CleanResourcesTask

### ISSUE THREAD

**Issue by ghost** [hazelcast/hazelcast-nodejs-client#775]
The tracking issue for the Java side PR.

**Fix exit condition in client CleanResourcesTask**

See https://github.com/hazelcast/hazelcast/pull/17618 for details.

---

The loop was exiting too early if connection was closed for one of pending invocations

**Comment by puzpuzpuz** [comment]
Closing as Node.js client has this fix.
