### ISSUE TITLE
[TRACKING ISSUE] Adding clientname tag to client metrics

### ISSUE THREAD

**Issue by ghost** [hazelcast/hazelcast-nodejs-client#778]
The tracking issue for the Java side PR.

**Adding clientname tag to client metrics**

See https://github.com/hazelcast/hazelcast/pull/17654 for details.

---

Adds the client name to every metric related to clients. It was requested in https://hazelcast.zendesk.com/agent/tickets/6637

**Comment by puzpuzpuz** [comment]
Closing as the fix was on server-side.
