### ISSUE TITLE
[TRACKING ISSUE] Send -1 instead Long.Max for leasetime by default

### ISSUE THREAD

**Issue by ghost** [hazelcast/hazelcast-nodejs-client#779]
The tracking issue for the Java side PR.

**Send -1 instead Long.Max for leasetime by default**

See https://github.com/hazelcast/hazelcast/pull/17676 for details.

---

fixes https://github.com/hazelcast/hazelcast/issues/17637

**Comment by puzpuzpuz** [comment]
Closing as Node.js client does that.
