### ISSUE TITLE
[TRACKING ISSUE] Check duplicate fields when building class definition

### ISSUE THREAD

**Issue by ghost** [hazelcast/hazelcast-nodejs-client#780]
The tracking issue for the Java side PR.

**Check duplicate fields when building class definition**

See https://github.com/hazelcast/hazelcast/pull/17682 for details.

---

ClassDefinitionBuider.addX methods checks if a field
is already added with same name and
throws HazelcastSerializatioException if already added.

fixes https://github.com/hazelcast/hazelcast/issues/17616

**Comment by puzpuzpuz** [comment]
Not applicable as Node.js client doesn't have class definition programmatic API.
