### ISSUE TITLE
[TRACKING ISSUE] Release acquired FencedLock sessions before throwing

### ISSUE THREAD

**Issue by ghost** [hazelcast/hazelcast-nodejs-client#781]
The tracking issue for the Java side PR.

**Release acquired FencedLock sessions before throwing**

See https://github.com/hazelcast/hazelcast/pull/17697 for details.

---

Even if the calls to the lock, lockInterruptibly or tryLock
(or other variants of these methods) fail for some reason other than
SessionExpiredException or WaitKeyCancelledException, we were not
releasing the sessions we acquired in the beginning, before throwing
the exception. This fix aims to solve this problem by catching all
kinds of exceptions (other than the two mentioned above), releasing
the session and then rethrowing the catched exception.

**Comment by puzpuzpuz** [comment]
Closed with #642
