### ISSUE TITLE
[TRACKING ISSUE] Increase default cluster timeout to 2 minutes

### ISSUE THREAD

**Issue by ghost** [hazelcast/hazelcast-nodejs-client#785]
The tracking issue for the Java side PR.

**Increase default cluster timeout to 2 minutes**

See https://github.com/hazelcast/hazelcast/pull/18019 for details.

---

The old default tiemout was 20 seconds.
The change is done for environments like Kubernetes
where an Ip resolution/system restart could take
around a minute. We don't want a client to shutdown
in such cases, and we also want this to be out-of-the-box
behaviour.

Related config API

clientConfig.getConnectionStrategyConfig()
.getConnectionRetryConfig().getClusterConnectTimeoutMillis();

fixes https://github.com/hazelcast/hazelcast/issues/17904

**Comment by puzpuzpuz** [comment]
Closed with #744
