### ISSUE TITLE
[Polyglot Experience] Storing a Python list in a map and reading it on the NodeJS side fails

### ISSUE THREAD

**Issue by yuce** [hazelcast/hazelcast-nodejs-client#798]
Storing a Python list in a map and accessing that in the NodeJS client side causes a NodeJS exception. The same list can be accessed OK from the Java client.

Using Hazelcast 4.1.1.

Reproducer, Python side (Python client 4.0):
```python
hz = HazelcastClient()
polyglot_map = hz.get_map("polyglot").blocking()
polyglot_map.put("python-list", [1, 2, 3])
```
Python project is at: https://github.com/yuce/hazelcast-polyglot-experience/tree/main/python-project

NodeJS side (NodeJS client 4.1):
```javascript
(async () => {
    const client = await Client.newHazelcastClient();
    const polyglotMap = await client.getMap("polyglot");
    const pythonList = await polyglotMap.get("python-list");
    console.log(`pythonList: ${pythonList}`);
})();
```
The exception i get is:
```
Error running main TypeError: Cannot read property 'read' of undefined
    at SerializationServiceV1.toObject (/home/yuce/Work/hazelcast/blog_post/polyglot-hazelcast-experience/nodejs-project/node_modules/hazelcast-client/lib/serialization/SerializationService.js:85:27)
    at MapProxy.toObject (/home/yuce/Work/hazelcast/blog_post/polyglot-hazelcast-experience/nodejs-project/node_modules/hazelcast-client/lib/proxy/BaseProxy.js:102:54)
    at /home/yuce/Work/hazelcast/blog_post/polyglot-hazelcast-experience/nodejs-project/node_modules/hazelcast-client/lib/proxy/MapProxy.js:477:25
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async main (/home/yuce/Work/hazelcast/blog_post/polyglot-hazelcast-experience/nodejs-project/server.js:96:24)
    at async /home/yuce/Work/hazelcast/blog_post/polyglot-hazelcast-experience/nodejs-project/server.js:134:9
```

NodeJS project is at: https://github.com/yuce/hazelcast-polyglot-experience/tree/main/nodejs-project

Java client can correctly load the same Python list (Java client 4.1.1):
```java
HazelcastInstance hz = HazelcastClient.newHazelcastClient();
IMap<String, Object> polyglotMap = hz.getMap("polyglot");
Object pythonList = polyglotMap.get("python-list");
System.out.printf("pythonList: %s%n", pythonList);
```

Java project is at: https://github.com/yuce/hazelcast-polyglot-experience/tree/main/java-project

**Comment by puzpuzpuz** [comment]
@yuce could also describe how lists are serialized in Python. Namely, which [serializer](https://github.com/hazelcast/hazelcast-python-client/blob/f36567ca0477d3240f7041fe0b764d0b983eb6a5/hazelcast/serialization/serializer.py) is used for the list.

**Comment by yuce** [comment]
@puzpuzpuz It is the `ArrayListSerialiazer`: https://github.com/hazelcast/hazelcast-python-client/blob/f36567ca0477d3240f7041fe0b764d0b983eb6a5/hazelcast/serialization/serializer.py#L312

**Comment by puzpuzpuz** [comment]
@yuce thanks for reporting this issue. #799 should fix it

**Comment by yuce** [comment]
@puzpuzpuz Thanks for the quick fix!
