### ISSUE TITLE
Kill RC process after integration test execution

### ISSUE THREAD

**Issue by puzpuzpuz** [hazelcast/hazelcast-nodejs-client#803]
Currently Remote Controller process is kept alive after integration test suite passes. We need to make sure to kill the process once tests get executed or aborted.

**Comment by srknzl** [comment]
Maybe writing the pid to a file helps

**Comment by puzpuzpuz** [comment]
> Maybe writing the pid to a file helps

It could work. Or we could update the runner script which would run RC in a child process and make sure to kill it once tests pass or when a signal like SIGTERM is received.

**Comment by srknzl** [comment]
> > Maybe writing the pid to a file helps
> 
> It could work. Or we could update the runner script which would run RC in a child process and make sure to kill it once tests pass or when a signal like SIGTERM is received.

Done! check #804
