### ISSUE TITLE
Cover ClientConnectionManager.getRandomConnection() with unit tests

### ISSUE THREAD

**Issue by puzpuzpuz** [hazelcast/hazelcast-nodejs-client#807]
We should add a simple unit test which validates `getRandomConnection` in smart/unisocket modes: load balancer has to be used for smart mode; unisocket mode has to pick up the first active connection.

Offtopic. We could also rename `ClientConnectionManager` class into `ConnectionManager` as `Client*` prefix doesn't provide any value for a client library.

**Comment by srknzl** [comment]
> We should add a simple unit test which validates `getRandomConnection` in smart/unisocket modes: load balancer has to be used for smart mode; unisocket mode has to pick up the first active connection.
> 
> Offtopic. We could also rename `ClientConnectionManager` class into `ConnectionManager` as `Client*` prefix doesn't provide any value for a client library.

My intention is to add both changes to the pr #797

**Comment by srknzl** [comment]
> Offtopic. We could also rename `ClientConnectionManager` class into `ConnectionManager` as `Client*` prefix doesn't provide any value for a client library.

Assuming same for ClientConnection

**Comment by puzpuzpuz** [comment]
> My intention is to add both changes to the pr #797

I've created this issue to avoid blocking that PR, but if you include the change, it would be great

**Comment by srknzl** [comment]
@puzpuzpuz would love to know what you think about the test I wrote in #797

**Comment by puzpuzpuz** [comment]
> @puzpuzpuz would love to know what you think about the test I wrote in #797

Reviewed the tests and left some comments. Thanks for adding them.

**Comment by srknzl** [comment]
Can be closed as part of #797

**Comment by puzpuzpuz** [comment]
Closed with #797
