### ISSUE TITLE
Specifying published files easier

### ISSUE THREAD

**Issue by srknzl** [hazelcast/hazelcast-nodejs-client#815]
We are using .npmignore file to ignore files from published. Some files always included as said in this link:
https://docs.npmjs.com/cli/v7/configuring-npm/package-json#files

What we can do instead is, add "files": "lib/" to package.json and delete .npmignore file. Keeping track of what to ignore is harder.

E.g You can see currently tsconfig.eslint.json is included in package when installed via `npm i hazelcast-client`

These are what is in the published files right now:

```
 lib
.npmignore
package-lock.json(this should be excluded normally unless npm-shrinkwrap.json is used)
tsconfig.eslint.json
LICENSE
package.json
README.md

```

**Comment by srknzl** [comment]
@puzpuzpuz @mdumandag Which files should we publish for Node.js client? Are we publishing any unnecessary files? (You can see them above)

For example why `tsconfig.eslint.json`, `package-lock.json` and `.npmignore` are published?

**Comment by puzpuzpuz** [comment]
> For example why `tsconfig.eslint.json`, `package-lock.json` and `.npmignore` are published?

These files do no harm when included into the published artifact, but they're leftovers, so we should make sure to exclude them.
