### ISSUE TITLE
Allowing use of numbers for config where long is needed

### ISSUE THREAD

**Issue by srknzl** [hazelcast/hazelcast-nodejs-client#912]
Originally suggested in this comment https://github.com/hazelcast/hazelcast-nodejs-client/pull/847#discussion_r639821348, this change will make configuring client easier.

**Comment by srknzl** [comment]
@mdumandag isn't this a breaking change? Users will need to update their configuration where they use a long to use a number instead. Do we really want to make this breaking change? WDYT?

**Comment by mdumandag** [comment]
I meant if the configuration element requires its type to be `Long`, make it `Long | number` so that it can be easier to use

**Comment by srknzl** [comment]
There are no other config that accepts only long
