### ISSUE TITLE
client.getMap(name) doesnt really return Promise<what you need in server>

### ISSUE THREAD

**Issue by LycheeHe** [hazelcast/hazelcast-nodejs-client#934]
**Describe the bug**
when I changed my hazelcast client from 4 to 3 version, means that I use version 3.12 to implement my hazelcast client version, and get see the log, seems fine to connect with the server which is written by java, and next step is to get map from server, so I call
`this.client.getMap(name).then(map => console.log(map))`

**Expected behavior**

and this is what I logged: 
![image](https://user-images.githubusercontent.com/30425557/121186509-beb4bf00-c899-11eb-8eb0-242831e86188.png)
the reason why I log 'keys' is that I think what I got is Map, so `map.keys()` is fine to get all keys of the map, but later I just logged mapResult.

**Environment (please complete the following information):**

1. Exact Node.js client version that you use (_e.g._ `4.1.0`):

2. Exact Hazelcast version that you use : **3.12.4**

3. Cluster size, _i.e._ the number of Hazelcast cluster members. **7**

4. Number of clients: just one

**To Reproduce**
1. 

**Additional context**

**Comment by mdumandag** [comment]
@LycheeHe the thing you printed to console is a client-side proxy of a distributed map that lives on the cluster. You cannot access the keys by printing the map. You should be using the methods like `map.get`, `map.keySet` etc. to access the data. You can take a look at all the methods available at http://hazelcast.github.io/hazelcast-nodejs-client/api/4.2.0/docs/interfaces/proxy_imap.imap.html

and to see a code sample, check the https://github.com/hazelcast/hazelcast-nodejs-client/blob/master/code_samples/map.js

**Comment by srknzl** [comment]
Also 4.x clients does not support 3.x server right? @mdumandag

**Comment by LycheeHe** [comment]
sorry, this is not a bug, but what I wrongly get the map, should be closed
