### ISSUE TITLE
hazelcast nodejs client serialization dosent support complex object

### ISSUE THREAD

**Issue by LycheeHe** [hazelcast/hazelcast-nodejs-client#936]
**Describe the bug**
my IMap is <Request, Response>, 
the Request:
`interface Request{ requestId: string, param: <some complexed type>, ... }`
`interface Response{ responseId: string, data: <some complexed data type>, ...}`
but after I connected with the java hazelcast server, and
`getMap(mapName).then(map => {
  map.keySet(keys => console.log(keys))
})`
and this will throw an error which happens in `SerializationService.js`, in `toObject()` function, the variable `serializer` is undefined, so, cant `return serializer.read(dataInput)`

**Expected behavior**
throw an error which happens in `SerializationService.js`, in `toObject()` function, the variable `serializer` is undefined, so, cant `return serializer.read(dataInput)`

**Screenshots**

**Environment (please complete the following information):**

2. Exact Hazelcast version that you use (_e.g._ `3.8.3`, also whether it is a minor release, or the latest snapshot):

**Comment by mdumandag** [comment]
@LycheeHe What serialization method you use for your objects? Not being able to find a serializer means that the client is unaware of the type of serializer you use. 

Are you putting these objects from Java, and trying to read them from the Node.js client? Or, are you just using the Node.js client with the IMDG server?

BTW: `getMap(mapName).then(map => { map.keySet(keys => console.log(keys)) })` should have been something like 
```js
client.getMap(mapName).then(map => {
        return map.keySet();
    }).then(keys => {
        console.log(keys);
    });
```

**Comment by mdumandag** [comment]
@srknzl we could improve the error message in this case a little bit.

https://github.com/hazelcast/hazelcast-nodejs-client/blob/master/src/serialization/SerializationService.ts#L144

If the serializer is undefined, we could throw HazelcastSerializationException

**Comment by srknzl** [comment]
@mdumandag I agree. We can improve error handling here. I will send a pr soon.

**Comment by LycheeHe** [comment]
ahaha, took a whole day to find serilization error, and I already saw the code_exmples/custom_serializer.js, and use mousse to serialize, and finally, doesnt receive error but the `map.keySet()` is empty, lol, it shouldnt be like this.
BTW, I need to raise another bug that, when I download the hazelcast-client, verison 3.12.4, and I cant use it directly, cuz `///` apprears on the top of most files, I need to manually change `///` to `//`,

**Comment by srknzl** [comment]
hmm why cant you use them directly? this seems interesting

**Comment by LycheeHe** [comment]
![image](https://user-images.githubusercontent.com/30425557/121718166-9258a700-cb14-11eb-90b1-94ce377d9d87.png)

some `///` like it will create when you build you code source, even when I download the src source and build it locally, this `///` will auto add after running `npm run build`

**Comment by srknzl** [comment]
why is it a problem? Typescript generates it to indicate a type definition dependency on another package

https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html#-reference-types-

**Comment by LycheeHe** [comment]
@srknzl  maybe IDE, vs Code and Intelij Idea dont support this dependancy

**Comment by srknzl** [comment]
@LycheeHe Is the main problem of this issue resolved?

**Comment by srknzl** [comment]
> ahaha, took a whole day to find serilization error, and I already saw the code_exmples/custom_serializer.js, and use mousse to serialize, and finally, doesnt receive error but the map.keySet() is empty, lol, it shouldnt be like this.
BTW, I need to raise another bug that, when I download the hazelcast-client, verison 3.12.4, and I cant use it directly, cuz /// apprears on the top of most files, I need to manually change /// to //,

closing as per the quoted comment of yours, thinking **this** issue is resolved, feel free to open another issues if there are others.
