### ISSUE TITLE
Getting error: TypeError: output.writeString is not a function in nodejs client

### ISSUE THREAD

**Issue by vjgn** [hazelcast/hazelcast-nodejs-client#942]
Hi I am using Sql predicate to query a Hazelcast map and running into this issue.    
Error info:   
```
TypeError: output.writeString is not a function
at SqlPredicate.writeData (/app/node_modules/hazelcast-client/lib/serialization/DefaultPredicates.js:41:16)
at IdentifiedDataSerializableSerializer.write (/app/node_modules/@atlas/sfdbbase/node_modules/hazelcast-client/lib/serialization/DefaultSerializers.js:352:16)
at SerializationServiceV1.toData (/app/node_modules/@atlas/sfdbbase/node_modules/hazelcast-client/lib/serialization/SerializationService.js:73:20)
at MapProxy.toData (/app/node_modules/@atlas/sfdbbase/node_modules/hazelcast-client/lib/proxy/BaseProxy.js:96:54)
at MapProxy.valuesWithPredicate (/app/node_modules/@atlas/sfdbbase/node_modules/hazelcast-client/lib/proxy/MapProxy.js:215:40)
```

The predicate used is very simple:    

```
async getFiles(transId: string, nextId: number|undefined): Promise<Array<IFilePointer>> {
    const client: Client = DIContainer.get<Client>(DB_DITYPES.HazelCast);
    const fileMap = await client.getMap('all.visdata');
    const predicate = Predicates.sql(`id = ${transId} and time > ${nextId}`);
    const result: ReadOnlyLazyList<IFilePointer> = await fileMap.valuesWithPredicate(predicate) as ReadOnlyLazyList<IFilePointer>; //<--- Error is thrown at this line
    return result.toArray().sort(this.Comparator);
}
```
Searched the internet for any possible clues or similar issues but could not find any. 
What could be causing this issue?

**Comment by mdumandag** [comment]
Hi @vjgn. I am not able to reproduce the issue with the latest master. What version of the client are you using?

**Comment by vjgn** [comment]
I must have mentioned the versions of server and client. My apologies.
Hazelcast server version: 4.1
Hazelcast NodeJS client version: 4.2.0

I did further testing and if I downgrade the client version from 4.2.0 to 4.1.0 the issue gets resolved and it works without any errors.
It is something to do with the compatibility between server 4.1 and client 4.2.0.

**Comment by srknzl** [comment]
We tried this code snippet to reproduce your problem, but we could not:
```js
'use strict';
const { Client, Predicates } = require('hazelcast-client');
(async () => {
    const client = await Client.newHazelcastClient();
    const map = await client.getMap('test');
    const transId = 'test';
    const nextId = 5;
    const predicate = Predicates.sql(`id = ${transId} and time > ${nextId}`);
    console.log(await map.valuesWithPredicate(predicate));
})();
```

When I put a breakpoint [here](https://github.com/hazelcast/hazelcast-nodejs-client/blob/7aa5c241e4bd1b30f04fea6f419294424b4639f3/src/serialization/DefaultPredicates.ts#L56), output and output.writeString looks like the following:
![image](https://user-images.githubusercontent.com/32355782/122177807-a131b780-ce8e-11eb-8238-c318a8a9fa07.png)


Can you debug as well, with your code and with the code we tried, to see if the issue will exist on both?  Also, you can debug after downgrading to 4.1 and see the difference.

Also you can share the following info that are missing in your issue to help us figure out the issue:
```
 Cluster size, _i.e._ the number of Hazelcast cluster members.

 Number of clients:

 Node.js version. It is also useful to mention `node` command line arguments if there are any:

 Operating system. If it is Linux, kernel version is helpful:

 Logs and stack traces, if available:
```
My environment:

Nodejs Client: 4.2.0
Node version: v12.16.3
OS: Linux serkan-PC 5.8.0-55-generic #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Cluster size: 1
# of clients: 1
Hazelcast version: 4.1 docker

**Comment by vjgn** [comment]
I debugged and here are my findings:

1) Sample program (with both version 4.1.0 and 4.20) -> works

Also output.writeString is a valid function as seen from below:
![image](https://user-images.githubusercontent.com/7349897/122296059-cf26f400-ceae-11eb-9a04-8553f368ad92.png)


2) My code, using 4.1.0 -> error
In this case output.writeString is undefined
![image](https://user-images.githubusercontent.com/7349897/122296150-ecf45900-ceae-11eb-9174-d06f04a72f58.png)

3) Here is the strange part. My code using 4.2.0 -> works
In this case, the function used is output.writeUTF instead of output.writeString. See below:
![image](https://user-images.githubusercontent.com/7349897/122296385-32b12180-ceaf-11eb-96de-8ba7b00eaac4.png)

Not sure how 4.2.0 of the client would have output.writeString in one case and output.writeUTF in another case.

Since the sample code works with both versions (4.1.0 and 4.20), I am leaning this to be some kind of build/packaging issue in my side. Will update if I determine the issue. For now, I am downgrading to 4.1.0 and proceeding.

Thanks for all your help and support.

**Comment by srknzl** [comment]
Thanks for taking time and debugging.

Just to make it clear, writeString methods are added in 4.2. `UTF` in methods are renamed to `String`. writeUTF still exists on 4.2.0 but they are deprecated. See #802 

Why do you use two separate versions of the client in the same code? 

In order to find main cause of this issue, I guess we need to learn how you are using two versions of the client in separate components of your code. Is your code open source, can you show it(at least simple reproducer)?

**Comment by vjgn** [comment]
Hi @srknzl  
Sorry could not reply to your questions earlier. 
The reason for two separate versions is because each component is maintained by different teams and minor version difference (of hazelcast-client versions) is expected for sometime. (We can do better coordination to close this gap though)

I was able to reproduce the issue with a simple code. See below:

Component 1   
index.js:   
```
'use strict';
const { Client } = require('hazelcast-client');

async function getClient() {
    return await Client.newHazelcastClient();
}

module.exports = { getClient }
```
package.json dependencies section:   
```
  "dependencies": {
    "hazelcast-client": "4.1.0"
  }
```


Component 2   
index.js   
```
const comp1 = require('comp1')
const { Client, Predicates } = require('hazelcast-client');

(async () => {
    const client = await comp1.getClient();
    const map = await client.getMap('test');
    const transId = 'test';
    const nextId = 5;
    const predicate = Predicates.sql(`id = ${transId} and time > ${nextId}`);
    console.log('Query return:', await map.valuesWithPredicate(predicate));
})();
```
package.json dependencies section:   
```
  "dependencies": {
    "comp1": "file:../comp1",
    "hazelcast-client": "4.2.0"
  }
```

When I do `npm install` in comp1 first and then comp2 and run comp2 using `node index.js`, then I get this error:
```
[DefaultLogger] INFO at LifecycleService: HazelcastClient is STARTING
[DefaultLogger] INFO at LifecycleService: HazelcastClient is STARTED
[DefaultLogger] INFO at ConnectionManager: Trying to connect to 127.0.0.1:5701
[DefaultLogger] INFO at LifecycleService: HazelcastClient is CONNECTED
[DefaultLogger] INFO at ConnectionManager: Authenticated with server 172.17.0.3:5701:72262089-9b4f-453a-9836-e3577552bbb2, server version: 4.1, local address: 127.0.0.1:57039
[DefaultLogger] INFO at ClusterService:

Members [1] {
        Member [172.17.0.3]:5701 - 72262089-9b4f-453a-9836-e3577552bbb2
}

(node:38924) UnhandledPromiseRejectionWarning: TypeError: output.writeString is not a function
    at SqlPredicate.writeData (D:\Dev\test\hazeltest\comp2\node_modules\hazelcast-client\lib\serialization\DefaultPredicates.js:41:16)
    at IdentifiedDataSerializableSerializer.write (D:\Dev\test\hazeltest\comp1\node_modules\hazelcast-client\lib\serialization\DefaultSerializers.js:352:16)
    at SerializationServiceV1.toData (D:\Dev\test\hazeltest\comp1\node_modules\hazelcast-client\lib\serialization\SerializationService.js:73:20)
    at MapProxy.toData (D:\Dev\test\hazeltest\comp1\node_modules\hazelcast-client\lib\proxy\BaseProxy.js:96:54)
    at MapProxy.valuesWithPredicate (D:\Dev\test\hazeltest\comp1\node_modules\hazelcast-client\lib\proxy\MapProxy.js:215:40)
    at D:\Dev\test\hazeltest\comp2\index.js:10:44
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:38924) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:38924) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by srknzl** [comment]
Thanks, I reproduced your problem.

If you really need to import the client instance from comp1, I would also import `Predicates` object as an easy fix. Since you are using 4.1.0 version of client with 4.2.0 version of `Predicates` object, incompatibility is inevitable. Is this easy fix ok for you? (Basically import `Predicates` or other required objects from comp1, too):

comp1:

```js
'use strict';
const { Client, Predicates } = require('hazelcast-client');

async function getClient() {
    return await Client.newHazelcastClient();
}

function getPredicates() {
    return Predicates;
}

module.exports = { getClient, getPredicates }
```

comp2
```
const comp1 = require('comp1');

(async () => {
    const client = await comp1.getClient();
    const Predicates = comp1.getPredicates();
    const map = await client.getMap('test');
    const transId = 'test';
    const nextId = 5;
    const predicate = Predicates.sql(`id = ${transId} and time > ${nextId}`);
    console.log('Query return:', await map.valuesWithPredicate(predicate));
})();
```

Note that if versions of the clients in two components swapped, the issue would not happened because in that case writeUTF method would be used. 4.2.0 version of SQL Predicate object uses `writeString` in its `readData` and `writeData` methods. Once created, it cannot be changed; its implementation of `readData` or `writeData` will be used. 


Maybe we can revert `readString` in SqlPredicate(same for other predicates) to `readUTF`. WDYT @mdumandag ?

**Comment by srknzl** [comment]
Please try to use my proposed workaround to solve the issue. We decided not to revert the renaming of api for such a rare use case(two clients being used and mixing imports of them together). Thanks for your understanding.

**Comment by vjgn** [comment]
@srknzl Thanks for letting me know your teams decision. For now we are managing our components to use the same version. Planning to use your advice when we implement future changes. Thank you for your support.
