### ISSUE TITLE
Documentation: SQL code samples should handle errors.

### ISSUE THREAD

**Issue by utkukaratas** [hazelcast/hazelcast-nodejs-client#983]
(it's highly likely the code will throw due to some wrong sql expression so ... just for convenience. also it would answer if there's a special Exception class to catch or not.)

**Comment by srknzl** [comment]
Is this change work for you? Do you want something like this? https://github.com/hazelcast/hazelcast-nodejs-client/pull/974/commits/f78af81af61d7f2c6ee7a53c3d7cd4a61c77a2d8

**Comment by utkukaratas** [comment]
@srknzl LGTM.

**Comment by srknzl** [comment]
Code samples updated in https://github.com/hazelcast/hazelcast-nodejs-client/pull/974
